### ISSUE TITLE
package run show output at real time

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#100]
Test:
```bash
mkdir test && cd test
echo -e "main()\n{\n\tprint(\"started\");\n\tsleep(10000);\n\tprint(\"10 seconds, exiting\");\n\n\tSendRconCommand(\"exit\");\n}\n" > test.pwn
echo -e "{\n\t\"entry\": \"test.pwn\",\n\t\"output\": \"test.amx\",\n\t\"dependencies\": [\n\t\t\"sampctl/samp-stdlib\"\n\t]\n}\n" > pawn.json
clear
ls
cat pawn.json
cat test.pwn
sampctl package run --forceEnsure --forceBuild
tail -6 ~/.samp/runtime/0.3.7/server_log.txt
```
This will show the `started` only after 10 seconds

**Comment by Southclaws** [comment]
The output from the server *is* realtime, there's no artificial delay - it simply pipes the output to stdout. The delay you're experiencing could be a number of things: if it's the first compile, it'll download the compiler, if it's the first run on that version (default 0.3.7) it will download the runtime etc. Try building first then running separately. I'll test this myself when I get back to a Windows machine.

**Comment by Dayvison** [comment]
`it simply pipes the output to stdout.` this happens only when the server shutdown. Is this what i mean

**Comment by Southclaws** [comment]
What platform have you been testing on? I did notice issues with Linux during some [Travis tests](https://travis-ci.org/Southclaws/samp-ini/builds) though and I expected it was related to buffer flushing. I've not noticed this issue on Windows but I've not done any time-sensitive tests, just quick `main()` runs and y_testing.

However, server runtime works as expected (I was running a gamemode with `sampctl server run` for a few months and output was fine) so I'm not sure what's going on here.

**Comment by Dayvison** [comment]
I'm using linux.

http://showterm.io/22ce770fab9e8dcfe046f

**Comment by Southclaws** [comment]
Okay I've reproduced this in Docker (Ubuntu 16.04) and I have no idea why it happens...

Windows works as expected:

![2018-01-29_09-05-03](https://user-images.githubusercontent.com/1636971/35502007-86cd4c84-04d3-11e8-85ae-b5433060366e.gif)

I will have to do some more digging into how the Linux and Windows stream/buffer implementations differ in Golang...

**Comment by Southclaws** [comment]
@Dayvison how many CPU cores has your linux machine got? Is it a virtual machine or a containerised OS?

**Comment by Dayvison** [comment]
2, and linux is what i have installed on the machine

**Comment by Southclaws** [comment]
I haven't made any progress with this, but I'm putting this here for next time I try to tackle it.

> [12:53 PM] Y_Less: @Southclaws stdbuf -oO /root/.samp/runtime/0.3.7/samp03svr > mygoapp(edited)

**Comment by Southclaws** [comment]
Okay so using `unbuffer` is working, it's not ideal as it requires the user to `apt install expect` but it'll do for now (at least this will get unit tests working on CI).

I will also investigate this pseudo-terminal lib in future: https://github.com/kr/pty

**Comment by Southclaws** [comment]
I may have fixed this in the dev branch, if you would like to test let me know.

I've also temporarily removed the crashloop restart feature, I'm not too sure exactly how many people were using it for production servers (probably none) but I plan to re-implement it in future.

**Comment by Dayvison** [comment]
Working now, but the sampctl process don't exit when server shut down.

http://showterm.io/443bbbac4539629fcc39e

**Comment by Southclaws** [comment]
Ah damn, that must be `unbuffer` not closing the process, I thought I resolved that. The problem here is that sampctl owns the `unbuffer` process but not the `samp03svr` process (`unbuffer` owns that) and closing `unbuffer` doesn't appear to close `samp03svr` - there may be a way to do this with a different signal? I tried `sigkill` and `sigint` already.

I'm going to try the pseudoterminal in pure Go instead as that would be the preferred option if it works.

**Comment by Southclaws** [comment]
Okay the latest commit seems to have fixed it! I'm so glad https://github.com/kr/pty exists!

Just going to do some more testing and then if it works fine for you, I'll merge it to master and release it to 1.6.9!

**Comment by Southclaws** [comment]
Okay this will take a bit longer to make it into master as the pty library is Linux only I need to re-organise the codebase a bit so I can set up build tags so portions of the sampctl code can target specific platforms.

I've never dug into build tags and platform-specific code in Go before so this will take some learning and time!

For now, you'll just have to use the dev branch for Linux.

**Comment by Southclaws** [comment]
Pushing this into 1.6.9 now, it should be fine and the samp-ini unit tests should be a good indicator of that.

**Comment by Southclaws** [comment]
Pawn package Linux unit tests passing, it's fixed! https://travis-ci.org/Southclaws/samp-ini/builds/330838413
