### ISSUE TITLE
Include files from runtime section when avaible

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#102]
The reason is some plugins  use `*.inc.in` in repo and when compile the plugin generates a true `*.inc` file 

Example MySQL plugin
https://github.com/pBlueG/SA-MP-MySQL/blob/c20296203cf8c1237dc61005c32d0e0389b558e9/pawn.json#L9
https://github.com/pBlueG/SA-MP-MySQL/blob/c20296203cf8c1237dc61005c32d0e0389b558e9/src/CMakeLists.txt#L18-L22

**Comment by Southclaws** [comment]
Yes this was the plan when I implemented the `includes` field to the `resource` object. I will hopefully get this into a 1.6 release so the MySQL plugin can be used properly.
