### ISSUE TITLE
Normalise build output paths

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#104]
From #99 by @Dayvison:

> * Show only the path after workingDir
> * Show the correct the paths, remove symlinks
> 
> This will be:
> ```
> dependencies/YSI-Includes/YSI_Data/y_iterate.inc:00 (warning) **
> source/main.pwn:00 (warning) **
> ```
> Instead
> ```
> /home/user/path/to/dependencies/YSI-Includes/YSI\..\YSI_Data\y_iterate.inc:00 (warning) **
> /home/user/path/to/source/main.pwn:00 (warning) **
> ```

This issue encompasses:

- normalising paths to use one directory separator and expanding all instances of `../`

Changing output to use relative paths instead of absolute paths is a breaking change for editors and will wait until the 1.7 release.

**Comment by Southclaws** [comment]
Going to close this, it would cause too many problems with very little gain.

- vscode problem matcher would need to be changed
- including files outside of the package directory would be impossible

**Comment by Dayvison** [comment]
I think a solution for this, is add a check if folder `.vscode` exists.
This kill the readability in every case of use except in vscode.

**Comment by Southclaws** [comment]
It's nothing to do with a bug, it's just simple compatibility.

**Comment by Dayvison** [comment]
This might help
```diff
diff --git a/compiler/compiler.go b/compiler/compiler.go
index 8bd97d4..bbe323e 100644
--- a/compiler/compiler.go
+++ b/compiler/compiler.go
@@ -187,6 +187,17 @@ func CompileWithCommand(cmd *exec.Cmd, workingDir string) (problems types.BuildP
 					problem.File = filepath.Join(workingDir, groups[1])
 				}
 
+				if string(filepath.Separator) != "\\" {
+					problem.File = strings.Replace(problem.File, "\\", "/", -1)
+				}
+
+				problem.File = filepath.Clean(problem.File)
+				
+				if absolutePath {
+					pwd, _ := os.Getwd()
+					problem.File = strings.TrimPrefix(problem.File, pwd + string(filepath.Separator))
+				}
+
 				problem.Line, _ = strconv.Atoi(groups[2])
 
 				switch groups[3] {

```
