### ISSUE TITLE
failed to create new zlib reader after failed attempt at gzip: zlib: invalid header

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#105]
`failed to create new zlib reader after failed attempt at gzip: zlib: invalid header`

This occurs when i try to get `urShadow/Pawn.CMD` and `urShadow/Pawn.Regex` linux plugins, i think is a limitation of zlib because i extracts and compressed the `*.so` again in `.samp/plugins/Pawn.*/latest` and worked

**Comment by Southclaws** [comment]
I remember having issues with this before, it looks like urShadow uses an archive format not supported by the archive library. Annoyingly it's only urShadow's repos that cause this issue...

**Comment by mshaugh** [comment]
```bash
pawncmd-3.1.4-linux.tar.gz: POSIX tar archive (GNU)
pawnraknet-1.0.2-linux.tar.gz: POSIX tar archive (GNU)
```

[urShadow/Pawn.CMD](https://github.com/urShadow/Pawn.CMD) and [urShadow/Pawn.RakNet](https://github.com/urShadow/Pawn.RakNet) releases are just tarballs, without any compression.

Now I've never written in golang, but looking at [download/extract.go](https://github.com/Southclaws/sampctl/blob/master/download/extract.go), it looks like `Untar` is only attempting to extract tarballs that are either gzip or zlib compressed. [mholt/archiver](https://github.com/mholt/archiver) may be of use?

**Comment by Southclaws** [comment]
That explains a lot, I didn't consider non-compressed archives. I will look into a solution for this and bump it into a 1.7 release so it's available sooner. Thanks!

**Comment by seanny** [comment]
I'm having this issue also with Pawn.CMD (Linux)

```WARN: failed to ensure plugin github.com/urShadow/Pawn.CMD failed to extract plugin github.com/urShadow/Pawn.CMD to /home/seanny/sampctl: failed to create new zlib reader after failed attempt at gzip: zlib: invalid header```

**Comment by urShadow** [comment]
Fixed.

**Comment by Southclaws** [comment]
I should document that .tar.gz and .zip are the only supported formats. But it seems like, now that Pawn.CMD uses a tar.gz, every plugin uses one of the two supported formats. So I'm going to close this for now.
