### ISSUE TITLE
Implement a backup system for server config and scriptfiles state

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#111]
It seems most backup solutions are bespoke. They usually come in the form of a badly written Bash script that only the author understands.

It would be useful if sampctl could periodically back up the configuration and scriptfiles directory (maybe other locations?).

This could be done by archiving the target files in a separate thread and either storing them to a directory (quick and dirty solution) or pushing them to an S3 bucket (common solution).

**Comment by Y-Less** [comment]
git?

**Comment by Southclaws** [comment]
This is for backing up server data, not source code. Think data files, maps, config, etc. Large stuff that might not fit the use-case of git. However, git could be a neat option for smaller servers, and is definitely possible since sampctl already has a built-in git client.

**Comment by Southclaws** [comment]
I'll now just direct users with this concern to https://github.com/restic/restic
