### ISSUE TITLE
Provide a way to support multiple plugin releases from a single dependency

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#118]
IRC Plugin provides SSL and Non-SSL versions, currently, sampctl does not support this.

More info/brainstorming:

> [10:52 PM] Southclaws: [10:06 PM] spacemud: @Southclaws how might you write a pawn.json for something like https://github.com/samp-incognito/samp-irc-plugin/releases ? where each version has a ssl and non-ssl variant?
> 
> good question @spacemud - I have no idea...
> GitHub
> samp-incognito/samp-irc-plugin
> samp-irc-plugin - IRC Plugin for SA-MP (San Andreas Multiplayer)
> 
> [10:52 PM] Southclaws: I'll have to think about that one... resources can specify multiple but currently the only "selector" is the operating system
> [10:55 PM] Southclaws: so I might need to introduce new syntax for a plugin dependency, something like:
> samp-incognito/samp-irc-plugin&ssl
> samp-incognito/samp-irc-plugin&non-ssl
> then add a label field to the resource definition, like:
>         {
>             "name": "^samp-irc-plugin-1.4.8-ssl.zip$",
>             "platform": "linux",
>             "label": "ssl",
>             "archive": true,
>             "plugins": ["plugins/irc.so"]
>         },
> (edited)
> [10:56 PM] Southclaws: where the & allows you to specify a label which is used to select an object from the resources field

**Comment by spacemud** [comment]
Can't believe it took this long for me to realise but turns out there's no issue here - as Incognito tagged each release separately with `ssl` or `non-ssl` you can specify the version you want in the dependency string: 

```
"samp-incognito/samp-irc-plugin:v1.4.8-non-ssl"
```

**Comment by Southclaws** [comment]
Oh that's good to know!

Still, I think the feature would be useful so I'll leave it open and eventually implement it anyway!

**Comment by Southclaws** [comment]
Actually screw it, I've got enough to do already!
