### ISSUE TITLE
Add SA-MP version for URM GTA: Criminal Russia

### ISSUE THREAD

**Issue by pawnoholic** [Southclaws/sampctl#119]
is it possible to add server support for the most popular adaptation sa-mp for URM GTA: Criminal Russia.

Official Thread: http://forum.sa-mp.com/showthread.php?t=155070

The executable file names are different from SA-MP

[Criminal Russia Multiplayer Rev C3 Windows Server](http://www.gtasrv.ru/download-srv/srv-cr-mp-c3-win.zip)
[Criminal Russia Multiplayer Rev C3 Linux Server](http://www.gtasrv.ru/download-srv/srv-cr-mp-c3-linux.tar.gz)

**Comment by Southclaws** [comment]
This is something I'm very interested in supporting 👍 

I've had a few people ask, so I will add support for custom endpoints soon.

I think the best way to do this would be to move all the hard-coded URLs for SA:MP versions out of the source code and into a JSON file hosted on GitHub which users could then modify to contribute custom servers such as Criminal Russia or RW-MP.

It will be similar to Homebrew's "Taps", APT's "Repositories" or Scoop.sh's "Buckets" systems.

**Comment by Southclaws** [comment]
Please submit a pull request to this file: https://github.com/sampctl/runtimes/blob/master/runtimes.json this is now where sampctl 1.7 will read download links for servers from.
