### ISSUE TITLE
Add support for local plugins

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#121]

**Comment by Dayvison** [comment]
I think this work only for `samp.json`, i mean in both `pawn.json` and `samp.json` sorry for not explain that

**Comment by Southclaws** [comment]
Ah yeah, this technically works with `pawn.json` too, as the `runtime` is just an instance of `samp.json` embedded.

However, the `plugins` field will be relative to the temporary runtime directory (which is in `~/.samp/runtime/...`) so you'd have to copy the .so/.dll to that directory.

I could make this relative to the *package* directory, but I'll need to think about it.

**Comment by Dayvison** [comment]
Oh, my bad. I was adding the `plugins` array out of `runtime` dict
