### ISSUE TITLE
sampctl server run doesn't ensure remote plugins

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#122]
> [2:09 PM] michaelbelgium: when i do ensure my plugins are plugins discord-connector.so SAMPSON.so crashdetect.so mysql.so sscanf.so streamer.so
> [2:09 PM] michaelbelgium: when i wanna run it , it changes to plugins discord-connector.so SAMPSON.so
> [2:10 PM] michaelbelgium: those 2 files are custom ones and not from github tho
> [2:10 PM] michaelbelgium: others are

**Comment by MichaelBelgium** [comment]
Just a thought as i can't test it right now but would `sampctl server run --ensurePlugins` maybe prevent this?

**Comment by Southclaws** [comment]
There are two stages to "ensuring" plugins - one is to generate the actual configuration and the other is to download the "remote" plugins. Somewhere in that, it's only processing one half of the plugin list (the local ones) and doesn't add the remote ones to the list.

Shouldn't be a difficult one to figure out. I'm still not sure how this missed unit tests though...
