### ISSUE TITLE
--watch does not recursively watch directory contents

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#135]
Only .pwn/.inc files in the package root are watched for changes, this means typical server setups or complex libraries don't work. This should be done either by watching the `entry` file too or recursively adding all sub directories to the watcher (possibly resource intensive).

**Comment by C-far** [comment]
The build watcher only compiles once when the output file is in a folder.

**Comment by Southclaws** [comment]
> The build watcher only compiles once when the output file is in a folder.

This also seems to be fixed with 1.7.13.
