### ISSUE TITLE
Issue with "--dir"

### ISSUE THREAD

**Issue by BigETI** [Southclaws/sampctl#14]
This is what I get, when I attempt to start a server:
```
Starting server process './samp-server.exe'...
Exited with error: exec: "./samp-server.exe": file does not exist
```
`samp-server.exe` is in that working directory specified in `--dir`.

**Comment by Southclaws** [comment]
Fixed in new version.

**Comment by Southclaws** [comment]
should be resolved now, let me know if it persists.
