### ISSUE TITLE
Warn while trying to ensure package Hual/SAMPSON

### ISSUE THREAD

**Issue by Crytrax** [Southclaws/sampctl#147]
`sampctl package ensure` outputs the following:
>WARN: Crytrax/E505-XF Failed to resolve package resource paths: failed to stat target path C:\Users\User\Desktop\E505\E505 Git\E505-XF\dependencies\extracted-asset-resources\SAMPSON-8eb02319cad844897df49c88b940a970: CreateFile C:\Users\User\Desktop\E505\E505 Git\E505-XF\dependencies\extracted-asset-resources\SAMPSON-8eb02319cad844897df49c88b940a970

when trying to fetch `Hual/SAMPSON`

The following directory is missing: `./dependencies\extracted-asset-resources\SAMPSON-8eb02319cad844897df49c88b940a970`

`sampctl package ensure` verbose output
>INFO: github.com/Hual/SAMPSON package already exists at 460e1b601a188ae1fd2d724363fdca6fc7540393 refs/heads/master
INFO: github.com/Hual/SAMPSON updating dependency package
INFO: github.com/Hual/SAMPSON updating repository state with <nil> authentication method
INFO: github.com/Hual/SAMPSON package does not have version constraint pulling latest
INFO: github.com/Hual/SAMPSON successfully checked out to 460e1b601a188ae1fd2d724363fdca6fc7540393
INFO: Crytrax/E505-XF successfully ensured dependency files for github.com/Hual/SAMPSON

### pawn.json:
```
{
	"user": "Crytrax",
	"repo": "E505-XF",
	"entry": "Main.pwn",
	"output": "Main.amx",
	"dependencies": [
		"samp-incognito/samp-streamer-plugin",
		"Southclaws/samp-camera-sequencer",
		"Southclaws/samp-logger",
		"ICJefferson/SA-MP-FileManager",
		"pawn-lang/YSI-Includes",
		"Y-Less/PAWN_PP",
		"sampctl/samp-stdlib",
		"maddinat0r/sscanf",
		"urShadow/Pawn.CMD",
		"BigETI/pawn-map",
		"IllidanS4/YSF",
		"Hual/SAMPSON"
	],
	"builds": [
		{
			"name": "FileManager",
			"includes": [
				"dependencies/SA-MP-FileManager"
			]
		}
	]
}
```

**Comment by Southclaws** [comment]
Odd, I can't reproduce this at all. I'll give it another shot later, I'm assuming you're on Windows?

**Comment by Southclaws** [comment]
I think I figured this one out, it's basically #149 and I should be able to fix it.

It's not blocking you from actually using the tool is it? If so that might be an error leak, it shouldn't as it's just a warning but I'd like to know because it shouldn't stop the process from completing at all.

If it does actually stop the process from completing, make sure the last dependency in your JSON is a "safe" dependency that doesn't break - such as samp-stdlib or my logger library.
