### ISSUE TITLE
Illegal Character Nul

### ISSUE THREAD

**Issue by JesterlJoker** [Southclaws/sampctl#151]
- WARN: failed to ensure package github.com/maddinat0r/samp-discord-connector: failed to open dependency repository: 1:1: illegal character NUL (and 2 more errors)

I then compared maddinat0r's sscanf/pawn.json which you created and samp-discord-connector/pawn.json which seanny created.

and saw the difference on how it was created, is it safe to say that the warning is within samp-discord-connector/pawn.json? since sscanf doesn't give me this warning.

**Comment by Southclaws** [comment]
I can't reproduce this:

```bash
9:05 southclaws@corax /Users/southclaws/Desktop/tmp
% sampctl package install maddinat0r/samp-discord-connector
INFO: Southclaws/tmp successfully ensured dependency files for github.com/maddinat0r/samp-discord-connector
INFO: successfully added new dependency
9:05 southclaws@corax /Users/southclaws/Desktop/tmp
% sampctl package ensure
INFO: Southclaws/tmp successfully ensured dependency files for github.com/maddinat0r/samp-discord-connector
INFO: ensured dependencies for package
```

**Comment by Southclaws** [comment]
Closing as stale, if you run into issues a good solution is to just delete the `dependencies` directory and cache directory named `.samp` that's located in your user folder.
