### ISSUE TITLE
Errors not displayed without terminal "sampctl package build"

### ISSUE THREAD

**Issue by Chipardeur** [Southclaws/sampctl#159]
Hey,
I think there is a problem when compiling w/o the terminal. 
![code_2018-05-03_19-53-59](https://user-images.githubusercontent.com/10562517/39594031-d308742a-4f0b-11e8-821e-d09db2b7b96b.png)
As you can see on the screenshot, terminal tells me that there is some errors in my code.
![code_2018-05-03_19-55-27](https://user-images.githubusercontent.com/10562517/39594083-f669273e-4f0b-11e8-8557-e975373588e2.png)
But none are send to the problems output.
Don't know if this is normal but I'm opening an issue to see with you.
Bye.

**Comment by Chipardeur** [comment]
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build only",
            "type": "shell",
            "command": "sampctl package build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "isBackground": false,
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated"
            },
            "problemMatcher": "$sampctl"
        },
        {
            "label": "build watcher",
            "type": "shell",
            "command": "sampctl package build --watch",
            "group": "build",
            "isBackground": true,
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated"
            },
            "problemMatcher": "$sampctl"
        },
        {
            "label": "run tests",
            "type": "shell",
            "command": "sampctl package run",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "isBackground": true,
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated"
            },
            "problemMatcher": "$sampctl"
        },
        {
            "label": "run tests watcher",
            "type": "shell",
            "command": "sampctl package run --watch",
            "group": "test",
            "isBackground": true,
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated"
            },
            "problemMatcher": "$sampctl"
        }
    ]
}`

**Comment by Southclaws** [comment]
Cannot reproduce with latest version.
