### ISSUE TITLE
Unify `package` and `server` Commands Somehow

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#165]
This has been a bit of a confusing element of sampctl recently. Users who just write and run gamemodes for live servers expect plugin installations to "just work".

## The Problem

As far as I can tell, the main confusion comes from the existence of two configuration files: `pawn.json` and `samp.json` - even though `pawn.json` can actually contain an instance of runtime configuration that's present in `samp.json`.

This is because `package` is designed primarily for:

- Writing *and* running packages
- Writing gamemodes

The issue here is that `package` cannot be used to *run* gamemodes - well, not properly...

## Running Code

This is because when you "run" a package, the workflow is designed to minimise the amount of barriers for *library* developers, not *gamemode* developers. Because of this, it creates a temporary runtime in `~/.samp/runtimes` and uses that to execute the package code as if it were a gamemode - as well as this, it also generates some standard default server config that includes 7777 as the port, `test` as the RCON password, etc.

`package` commands make it super easy to install plugins, because plugins are packages too. And when you `run` a package, it automatically resolves all the necessary plugins and puts them in that `~/.samp/runtimes` folder ready for running.

I think the best solution here would be to somehow allow packages to be run from the current directory, *not* `~/.samp/runtimes`.

I'm thinking this could be done via a `pawn.json` field:

```json
{
  "...": "...",
  "local": true
}
```

Here, `local` (may change) indicates that this package should be run "locally" - as in, "in the current package directory". This would cause `package ensure` to also ensure:
- Server binaries
- `server.cfg` (generated from the `runtime` entry *or* `samp.json` - see below)
- Plugin binaries

---

## The `samp.json` File and `server` Commands

The question then is what to do about `samp.json` and `sampctl server *` commands?

I think it might be best to eventually phase these out and just use `pawn.json` and `sampctl package *` commands (maybe even change these to just `sampctl *` commands?).

This would simplify the overall process but slightly complicate the process of *just running a server*. Not all users want to participate in the package ecosystem and may just want a tool that can handle configuration and automatically restart their server on crashes (as well as provide an API when #20 is implemented). So for this reason, I could imagine the `server` command staying for this use-case.

---

I'd love some feedback on this from some of the early adopters and primary users of sampctl!

**Comment by DebjitZX** [comment]
Indeed, pawn.json can ensure all the necessary files including runtime and plugin files while using _package run_. I think that sampctl package run can be mixed with server ensure as package build is enough to test/build the package and server ensure only check for .amx file and it should check all other necessary runtime and plugin files along with it.

**Comment by Southclaws** [comment]
Another thing I was considering: in the same way that `package build x` will choose a specific build configuration, would multiple runtime configurations also be useful? For example:

```json
{
  "runtimes": [
    {
      "name": "debug",
      "plugins": ["mysql-debug"]
    },
    {
      "name": "live",
      "plugins": ["mysql"]
    }
  ]
}
```

Then you could run this with `sampctl package run debug` or `sampctl package run live`.

**Comment by Southclaws** [comment]
Working on this in https://github.com/Southclaws/sampctl/tree/issue-165
