### ISSUE TITLE
Impossible to update dependencies

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#169]
When a dependency version is changed to a *newer* version in `pawn.json`, sampctl does not pull the latest version to check the tags, it only checks the tags that are present, meaning it's impossible to move *up* through versions, only *down* (which is mostly useless).

This should be fixed by first attempting to find the tag, if it's not there then pull the latest copy of the repo and attempt again, if that fails then fail with the original error: `failed to satisfy constraint, 'x.y.z' not in [list of tags]`

**Comment by BigETI** [comment]
You can for example store everything from `https://api.github.com/repos/<user>/<repository>/releases/latest` into a JSON file, and compare from there the current version using the release tag.

**Comment by Southclaws** [comment]
I was considering using the API and caching results, I want to avoid hitting rate limits for larger projects though. A user has already hit an API rate limit once.
