### ISSUE TITLE
How to update with no scoop

### ISSUE THREAD

**Issue by surviveworld** [Southclaws/sampctl#172]
Hi!
Faced a problem that can't update the sampctl. Scoop install is not possible, it is likely that this is due to the fact that in my country blocked a huge number of foreign subnets. Tried to update through sampctl-installer, too did not work. The operation timed out.

**Comment by Southclaws** [comment]
You can update by simply downloading the latest binary for your platform from https://github.com/Southclaws/sampctl/releases and replacing your existing binary with it.

I will update the wiki page soon.

**Comment by surviveworld** [comment]
thx!
