### ISSUE TITLE
Implement a way to force sampctl to download binaries for both platforms

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#177]
Should this apply to just plugins or server binaries too?

**Comment by LashaKanteladze** [comment]
I appreciate it that you always improve every part of sampctl to give us the best tool.

**Comment by n0dai** [comment]
I think it can be cool to download both plugins and server binaries. Without the server binaries it's useless to have a different platform plugins.

**Comment by LashaKanteladze** [comment]
@Southclaws Hey, what time for are you gonna add that feature? Im not in a hurry but Im very very interested..

**Comment by Southclaws** [comment]
Now possible with `--platform` flag.
