### ISSUE TITLE
Don't create the "filterscripts" folder when not needed

### ISSUE THREAD

**Issue by n0dai** [Southclaws/sampctl#179]
Is this possible to not create the "filterscripts" folder when no filterscripts are specified in the pawn.json package configuration file?

Thank you.

**Comment by n0dai** [comment]
Did you introduced it?

**Comment by Southclaws** [comment]
No, this hasn't been implemented yet. Currently I'm not really focusing on new features for this project as it's rather stable and I have other projects and things to focus on.

However, if you make a pull request for this, I'd happily merge it!
