### ISSUE TITLE
Cache latest version of package for pawn.json reference

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#187]
This may solve two issues at once (maybe more). One of the core problems currently is not being able to use versions of plugins that pre-date the addition of a pawn.json file to the repository. When a package is cloned, it is checked out to the version specified in the dependency string (if any). If this checkout points to a time before pawn.json exists, it treats the package as if it were a "simple" package and not a "full" package. Which is technically incorrect because the package itself *is* defined, it's just that definition only exists in the future (from the checkout point).

I can think of a few solutions. One involves caching full-depth copies of repositories in ~/.samp/packages in a gopath style structure (`~/.samp/packages/Southclaws/samp-logger` for example). These copies should always be up to date and never in detached head mode.

This solves two problems:

- Cached copies would speed up the `ensure` process
- This would mean there is always an up-to-date `pawn.json` available

Implementing this would mean the current `ResolveDependencies` code must be rewritten to not walk the local `dependencies/` tree but to actually search the cache for all dependencies then walk *their* `pawn.json` files recursively.

This might result in `ResolveDependencies` actually performing a pre-flight ensure-like process before the package ensure to actually make sure all cached copies are available and up to date.

The problem here is when a `dependencies/` repo is outdated and `EnsureDependency` performs a pull, that would have to pull the cached copy instead of the local copy, then copy the contents to `dependencies/`.

The question here becomes: do `dependencies/` folders even need to be repositories? If their contents is being copied from a central cached repo, it could simply copy over *only* the contents rather than the .git folder too. However this means checking out the required version in the cached copy, copying it to `dependencies/` and then checking out the cached copy back to HEAD. That feels like too many moving parts for little gain (though that gain would be good for repos with large histories).

I'd like some feedback on this from the community and particularly from those who are experienced with git repos and more of the technical details this concerns.

**Comment by Y-Less** [comment]
git is distributed, so you could add the cache as a remote and pull from it normally, which would minimise package ensure code changes as you are still pulling from git.

**Comment by Y-Less** [comment]
Or maybe I misunderstood what you think the problem is - what you said sounds like that already, which doesn't to me seem like a bad thing.

**Comment by Y-Less** [comment]
Seems much easier to leave dependencies as repos, then you can simply check out from a specified commit without having to move the cached copy around in versions (which would be very brittle - ensuring two modes at once would break, and a bug could leave it at entirely the wrong commit).

**Comment by Southclaws** [comment]
Yeah, in hindsight I realise that makes a lot more sense to keep them as repos. Currently it's not pulling from any local copy (I don't even know how to do that, do you set a file path as a remote?) but that's an interesting idea I didn't think of.

**Comment by Y-Less** [comment]
Also, checking out, copying, and checking out again, is just reinventing the wheel of what git was designed to do.

**Comment by Southclaws** [comment]
There are some great speed ups coming from this update so far!

- 1.8.4 - clone all dependencies
  `sampctl p ensure  19.85s user 5.56s system 31% cpu 1:20.59 total`

- 1.8.4 - ensure all dependencies that are already at correct versions
  `sampctl p ensure  0.75s user 0.55s system 13% cpu 9.986 total`

- latest - clone all dependencies with an empty cache
  `sampctl p ensure  14.06s user 3.63s system 40% cpu 43.966 total`

- latest - clone all dependencies that are all cached
  `sampctl p ensure  0.32s user 0.15s system 35% cpu 1.322 total`

- latest - ensure all dependencies that are already at correct versions and cached
  `sampctl p ensure  0.18s user 0.05s system 23% cpu 0.986 total`
