### ISSUE TITLE
Repository is empty while pulling from cached copy

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#193]
It seems the cached copies of dependency repositories are becoming empty somehow:

```
WARN: failed to ensure package github.com/sampctl/samp-stdlib: failed to ensure dependency from cache: remote repository is empty
```

**Comment by itsToretto** [comment]
This is still not fixed until now, you can try with this:

`sampctl p install Southclaws/samp-plugin-mapandreas` 

Gives you the warning code: 

`WARN: failed to ensure package github.com/Southclaws/samp-plugin-mapandreas: failed to ensure dependency from cache: remote repository is empty`

**Comment by Southclaws** [comment]
Just delete the cached copy, this occurs when the clone is cancelled half way through either by network drop or user closing the process.

**Comment by AtraXaz** [comment]
> This is still not fixed until now, you can try with this:
> 
> `sampctl p install Southclaws/samp-plugin-mapandreas`
> 
> Gives you the warning code:
> 
> `WARN: failed to ensure package github.com/Southclaws/samp-plugin-mapandreas: failed to ensure dependency from cache: remote repository is empty`

I don't know if this fixes fixes your problem but this fixed mine calling some repos like streamer by incognito, sky by oscar, sscanf by maddinat0r... and also pblueg's mysql plugin

 There are two ways to add a repo through sampctl by version and by branch
by Branch
``` 
author/repo@master
```
then by version
```
author/repo:1.0.0
```

Usually I play around on both sides and also the no sided one. which is
```
author/repo
```

I don't know what's the difference

 but before I call streamer
with this 
```  samp-incognito/streamer ```
and this
``` samp-incognito/streamer:v2.9.4 ```
but got the error

until I tried this
``` samp-incognito/streamer@master ```

P.S

I am commenting through phone. I'll edit this ones I get on a computer... But I am assured this might be helpful for you... if not then, there might be other methods to do this... Also try deleting your .samp folder, copy your pawn.json config or just make a back up, then re init your project folder, then ensure all packages...

Tried that and it fixed... sky plugin...
