### ISSUE TITLE
`package run --container` still expects a samp.json

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#195]
Container code should be updated for `local` and the new pcx format.

**Comment by ADRFranklin** [comment]
I hope this is fixed soon, would be nice have another reason to use docker to run sa-mp servers.

I am forced to do it manually, which breaks the chain of automated git deployment.

**Comment by Southclaws** [comment]
This feature is only for development, it's not considered stable so don't use it in production.

For production, copy the TradeWars deployment - simply build a docker image from the sampctl image that includes your server files: https://github.com/TradeWars/gamemode/blob/master/Dockerfile and if you want to deploy everything at once as well as automate image updates, check out the TradeWars CI setup: https://github.com/TradeWars/deployment

**Comment by PixellUp** [comment]
`sampctl package install ... ` also expect `pawn.json/pawn.yaml` while `sampctl server init` generates `samp.json`.

**Comment by Southclaws** [comment]
`server` doesn't read `samp.json` and it's deprecated. Use `package` and `pawn.json`.
