### ISSUE TITLE
Private dependency problem

### ISSUE THREAD

**Issue by pawnoholic** [Southclaws/sampctl#196]
Hi, I can't authentication. How to set it up correctly? I already added SSH keys to my PC and github account.

Problem:
`WARN: failed to ensure package github.com/pawnoholic/private-package-name: failed to clone dependency repository: authentication required`

**Comment by pawnoholic** [comment]
Found information on the wiki page and use:
`git@github.com:pawnoholic/crmp-exciting-roleplay-framework.git`

Problem:
`WARN: failed to ensure package github.com/pawnoholic/private-package-name.git: failed to clone dependency repository: error creating SSH agent: "SSH agent requested but Pageant not running"`

**Comment by pawnoholic** [comment]
It working! I reconfigured it.

**Comment by Southclaws** [comment]
The SSH library I use for some reason wants Pageant on Windows instead of OpenSSH (which now comes with Windows anyway since update 1800something)

**Comment by pawnoholic** [comment]
New problem:
`WARN: failed to ensure package github.com/pawnoholic/private-package-name.git: failed to ensure dependency from cache: remote repository is empty`

**Comment by Southclaws** [comment]
The cached copy was broken during a failed update, delete `~/.samp/packages/pawnoholic/private-package-name` and re-try. Alternatively, passing `--forceUpdate` may also fix this.

I'll try and make sampctl automatically recover from this error in a future update.
