### ISSUE TITLE
Run time error 19 when starting server with sscanf

### ISSUE THREAD

**Issue by MetroShonen** [Southclaws/sampctl#199]
So i wanted to get the latest version of sscanf, which i did by doing `install package maddinat0r/sscanf:v2.8.2`. Everything worked fine, i got the sscanf subfolder in my dependencies folder, the user/repo in my pawn.json file in the plugins section, and i also have the .dll file in the plugins folder.
It succesfully ensures sscanf when i ask sampctl to ensure dependencies, so everything seems like it should work as intended.

Except when i actually `#include sscanf2` at the top of my file, and i try to run the server, i get `run time error 19: file or function not found`. When i make the include sscanf line a comment with //, the run time error doesn't happen.

I have no idea what's wrong, i have triple checked everything in my server folder, my pawn.json, everything, and i still don't get why it's giving me errors.

EDIT: It seems like pawn.json isn't automatically modifying server.cfg to include sscanf as a plugin. I manually edited samp.json to include sscanf, and the server loads the plugin, however, still if i try to include sscanf2 at the top of my gamemode i'll get runtime error 19 when running the server.

Here's my pawn.json file

```
{
	"user": "MetroShonen",
	"repo": "SAOIT",
	"entry": "gamemodes\\SAOIT.pwn",
	"output": "gamemodes\\SAOIT.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"pawn-lang/YSI-includes",
		"Southclaws/zcmd",
		"maddinat0r/sscanf:v2.8.2"
	],
	"runtime": {
		"version": "0.3.7",
		"mode": "server",
		"plugins": [
			"maddinat0r/sscanf"
		],
		"rcon_password": "password",
		"port": 7777
	}
}
```

Here is my server log when i don't manually edit samp.json to include sscanf

```
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

plugins = ""  (string)

Server Plugins
--------------
 Loaded 0 plugins.


Started server on port: 7777, with maxplayers: 10 lanmode is OFF.


Filterscripts
---------------
  Loading filterscript 'weapons.amx'...

--------------------------------------
 Weapon Spawner by FusiouS loaded
 Version: 1.0, Release 1
--------------------------------------
  Loaded 1 filterscripts.

Script[gamemodes/SAOIT.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0
```

Here is my server log when i manually edit samp.json to include sscanf

```
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team


Server Plugins
--------------
 Loading plugin: sscanf


 ===============================

      sscanf plugin loaded.

   (c) 2009 Alex "Y_Less" Cole

   0.3d-R2 500 Players "dnee"

 ===============================

  Loaded.
 Loaded 1 plugins.


Started server on port: 7777, with maxplayers: 10 lanmode is OFF.


Filterscripts
---------------
  Loading filterscript 'weapons.amx'...

--------------------------------------
 Weapon Spawner by FusiouS loaded
 Version: 1.0, Release 1
--------------------------------------
  Loaded 1 filterscripts.

Script[gamemodes/SAOIT.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0
```

EDIT: So i restarted vscode as administrator and did `sampctl package run` and it seems like everything went relatively smoothly, i'm not getting any runtime errors.
However if i do `sampctl server run` i keep getting runtime error 19 🤔 
Here's the server log with package run

```
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team


Server Plugins
--------------
 Loading plugin: maddinat0r/sscanf
  Failed.
 Loading plugin: sscanf


 ===============================

      sscanf plugin loaded.

         Version:  2.8.2

   (c) 2012 Alex "Y_Less" Cole

 ===============================

  Loaded.
 Loaded 1 plugins.


Started server on port: 7777, with maxplayers: 50 lanmode is OFF.


Filterscripts
---------------
  Loaded 0 filterscripts.

Number of vehicle models: 0
```

**Comment by Southclaws** [comment]
You've duplicated the `sscanf` plugin across `dependencies` and `plugins`. You only need to specify a dependency once, in the `dependencies` field.

**Comment by Southclaws** [comment]
The `samp.json`/`pawn.json` and `server`/`package` differences were confusing, so that's why `server` and `samp.json` were deprecated.

Read this for information: https://github.com/Southclaws/sampctl/wiki/samp.json-To-pawn.json
