### ISSUE TITLE
sampctl p run doesn't load plugins.

### ISSUE THREAD

**Issue by DAKYSKYE** [Southclaws/sampctl#206]
On update *1.8.15*, we know **--platform** problem was fixed. I tried **sampctl p run --platform=linux** just to test if it download linux platform plugins. After that, No plugin is loaded when I write *sampctl p run*.
That's my **pawn.json**
```json
{
	"user": "DAKYSKYE",
	"repo": "AFL",
	"entry": "gamemodes\\afl.pwn",
	"output": "gamemodes\\afl.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"pawn-lang/YSI-Includes",
		"zeex/samp-plugin-crashdetect:v4.19",
		"maddinat0r/sscanf:v2.8.2",
		"samp-incognito/samp-streamer-plugin:v2.9.3",
		"Awsomedude/easyDialog",
		"DAKYSKYE/New-SA-MP-callbacks",
		"Open-GTO/sa-mp-fixes",
		"BigETI/pawn-memory:2.0"
	],
	"local": true,
	"builds": [
		{
			"name": "main",
			"includes": [
				"legacy"
			]
		}
	],
	"runtime": {
		"version": "0.3.DL-R1",
		"mode": "server",
		"rcon_password": "password",
		"port": 7777,
		"maxplayers": 1000,
		"extra": {
			"useartwork": "1"
		}
	}
}
```
There is also screenshot
![image](https://user-images.githubusercontent.com/32128756/42631943-892c2408-8590-11e8-8ed9-53a5fc865156.png)

**Comment by Southclaws** [comment]
1.8.16 might have fixed this, just waiting for release to finish: https://travis-ci.org/Southclaws/sampctl/builds/403085071

**Comment by DAKYSKYE** [comment]
okay
