### ISSUE TITLE
ERROR: Platform empty

### ISSUE THREAD

**Issue by DAKYSKYE** [Southclaws/sampctl#209]
That's the first time I see that error. I'm too interested, by what is that caused.
I write:
```bash
sampctl p install DAKYSKYE/Nex-AC
```
or
```
sampctl p install DAKYSKYE/Nex-AC:v1.9.39
```
and then getting that error (**ERROR: Platform emtpy**)

I considered it was caused by not specifying *--platform*, but the result was still same.

[link to repository](https://www.github.com/DAKYSKYE/Nex-AC)

## Screenshot

![image](https://user-images.githubusercontent.com/32128756/42733330-9bff9ff0-87e4-11e8-868c-7c3b99be1e2b.png)

### Hope you will fix that issues as soon as it's possible, good wishes to you from me.

**Comment by Southclaws** [comment]
I can't reproduce this but I had another user report it on Windows. It *might* be fixed but I need to test on Windows.
