### ISSUE TITLE
Add linux distribution field for plugin dependencies

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#214]
Some packages are build tailored to a distribution and its dependencies, and using a generic build could result in the plugin failing to load in some distributions.

An example of this is [maddinat0r/samp-discord-connector](https://github.com/maddinat0r/samp-discord-connector/releases) which sampctl defaults to the generic Linux build. Its Debian 9 build uses `libssl1.1`, while the generic Linux build uses `libssl1.0`. This one was removed from Debian 9 APT repositories, leaving `libssl1.1` as the only one. The "solution" would be downloading the deb manually, but this hassle could be avoided if sampctl could tell which build to use.

I don't know much about this topic, but I don't know how hard it could be to detect the Linux distribution.

**Comment by Southclaws** [comment]
The only way I can think to do this would be to call `uname` and parse the output - messy.

I'm going to close this one for now because I can't really think of a good solution and static releases should solve this anyway.
