### ISSUE TITLE
failed to compile package entry: exit status 3221225781

### ISSUE THREAD

**Issue by Stone-Codes** [Southclaws/sampctl#219]
Got this error while i tried to build a basic script with just a main function.
> sampctl package build    
> WARN: Failed to load .env: open .env: The system cannot find the file specified.    
> Failed to find configuration C:\Users\\-\\.samp\config.toml    
> Failed to find configuration C:\Users\\-\\.samp\config.yaml    
> INFO: Package does not have any tags, consider versioning your code with: `sampctl package release`    
> failed to compile package entry: exit status 3221225781

I tried other scripts, but got the same error. Not sure if im missing something.
The OS is a Windows Server 2016. The executing user has administrator rights.

**Comment by Southclaws** [comment]
Run with `--verbose` and try to execute the `pawncc` command it outputs manually, there may be an invalid flag being passed.

Also post your `pawn.json` - specifically, the `build`/`builds` section.

**Comment by Stone-Codes** [comment]
Ok actually i found the error. After i used the pawncc command that i got through the verbose flag, it gave me some errors with missing expressions etc., so i tried it just with the input and output file-parameter in the console. That gave me the error, that the 2 dlls (msvcp120.dll and msvcr120.dll) where missing. So I installed the corresponding c++ redistributable. Now its working. Thanks for your hint with the verbose flag.
