### ISSUE TITLE
Convert hostnames to ip addresses

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/sampctl#221]
So with me using docker containers to run my gamemode, I have gotten to the point where attempting to get NPC's to join is just not a thing, and the reason for this is because they attempt to join on `127.0.0.1` which is not a valid network point in docker.

Another reason for this suggestion is because we can't use bind due to docker's ip address changing on each start. So that means that defining a fixed ip address will not work.

So the suggestion is that if we could define hostnames in `sampctl` and have it automatically convert it to the ip address if found on runtime. 

That way it makes launching servers in docker more manageable, and also allow for us to successfully connect NPC's to our server.

**Comment by Southclaws** [comment]
This is done at the network level and handled by the TCP stack so applications never need to do this explicitly.
