### ISSUE TITLE
Can't include bcrypt

### ISSUE THREAD

**Issue by c-mnzs** [Southclaws/sampctl#229]
I'm having getting bcrypt to work. I'm getting it from [this](https://github.com/lassir/bcrypt-samp) repository with the following command:

`$ sampctl p install lassir/bcrypt-samp`

I then add it under `dependencies`, in `pawn.json`:
```json

"dependencies": [
    "sampctl/samp-stdlib",
    ...
    "lassir/bcrypt-samp"
]
```

When I include it in the gamemode (`#include <bcrypt>`), I get an error message which states `cannot read from file bcrypt`.

**Comment by Southclaws** [comment]
Did you resolve this, if so, how?
