### ISSUE TITLE
Config file is regenerated upon execution

### ISSUE THREAD

**Issue by c-mnzs** [Southclaws/sampctl#232]
I tried to install crashdetect and this happened:

```INFO: Zeex/samp-plugin-crashdetect downloading plugin resource for windows
WARN: failed to ensure package github.com/Zeex/crashdetect: failed to ensure asset: failed to get plugin Zeex/samp-plugin-crashdetect from net: failed to get remote package definition file: GET https://api.github.com/repos/Zeex/samp-plugin-crashdetect: 403 API rate limit of 60 still exceeded until 2018-08-08 00:42:40 +0100 BST, not making remote request. [rate reset in 21m17s]````

**Comment by c-mnzs** [comment]
This does not allow me to run the server as `ensuring` fails. Every function used from dependencies won't work.

```
[debug] Run time error 19: "File or function is not found"
[debug]  PC_Init
[debug]  SSCANF_Init
[debug]  SSCANF_IsConnected
[debug]  SSCANF_Join
[debug]  SSCANF_Leave
[debug]  regex_new
[debug]  regex_match
[debug]  Now
[debug]  WP_Hash
[debug]  sscanf
[debug] Run time error 19: "File or function is not found"
[debug]  PC_Init
[debug]  SSCANF_Init
[debug]  SSCANF_IsConnected
[debug]  SSCANF_Join
[debug]  SSCANF_Leave
[debug]  regex_new
[debug]  regex_match
[debug]  Now
[debug]  WP_Hash
[debug]  sscanf
Script[gamemodes/main.amx]: Run time error 19: "File or function is not found"
is not found"```

**Comment by AGraber** [comment]
You're being rate limited because you're doing unauthenticated requests to GitHub's API, which has a lower rate limit than authenticated requests.

See this (github_token):
https://github.com/Southclaws/sampctl/wiki/Configuration#configuration-fields

**Comment by c-mnzs** [comment]
I realized I was being rate limited but had no idea how to fix it. Cheers.

I added `github_token` to `config.json`, but it keeps getting deleted everytime I `run` the package (the whole file is overwritten). Any idea how to fix this? I set it as ready-only to see if it'd fix but I got an error message:

```
ERROR: Failed to load or create sampctl config in C:\Users\CARLOS MENEZES\.samp: open C:\Users\CARLOS MENEZES\.samp\config.json: Access is denied.
ERROR: Failed to write updated configuration file to C:\Users\CARLOS MENEZES\.samp - open C:\Users\CARLOS MENEZES\.samp\config.json: Access is denied.
```

**Comment by c-mnzs** [comment]
![github token fail](https://i.imgur.com/NcauSHM.gif)

**Comment by c-mnzs** [comment]
I did not realize there was a new version. This does **not** happen in the newest version, no. I've just updated and it's working flawlessly.

**Comment by c-mnzs** [comment]
As I already told you, `config.json` was overwritten for no reason at all and I got blocked again. The beginning of the following gif shows it happening:

![argh](https://i.imgur.com/AdGj0qP.gif)

**Comment by c-mnzs** [comment]
Any news on this issue? I keep getting rate limited because the config file keeps regenerating.

**Comment by Southclaws** [comment]
I generally only work on stuff at the weekend now, I'll see if I can get some time tonight. You might be best to backdate temporarily.

**Comment by spacemud** [comment]
This was giving me issues too so I had a look. It would appear that Configor is overwriting the config file settings with environment variables despite them being unset:

```
Trying to load struct `Config`'s field `UserID` from env __do_not_set__
Trying to load struct `Config`'s field `Metrics` from env SAMPCTL_METRICS
Trying to load struct `Config`'s field `DefaultUser` from env SAMPCTL_DEFAULT_USER
Trying to load struct `Config`'s field `GitHubToken` from env SAMPCTL_GITHUB_TOKEN
Trying to load struct `Config`'s field `GitUsername` from env SAMPCTL_GIT_USERNAME
Trying to load struct `Config`'s field `GitPassword` from env SAMPCTL_GIT_PASSWORD
Trying to load struct `Config`'s field `CI` from env CI
Trying to load struct `Config`'s field `NewUser` from env __do_not_set__
Configuration:
  &types.Config{UserID:"", Metrics:false, DefaultUser:"", GitHubToken:"", GitUsername:"", GitPassword:"", CI:"", NewUser:false}
```

**Comment by Southclaws** [comment]
Should be solved now, tested on Sunday's release and it all worked fine.
