### ISSUE TITLE
Ensuring fails on CentOS 7

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#234]
```
[root@localhost samp-bare]# sampctl p ensure
INFO: Usage metrics are active. See https://github.com/Southclaws/sampctl/wiki/Usage-Metrics for more information.
WARN: failed to ensure package github.com/sampctl/samp-stdlib: failed to ensure dependency from cache: unknown error: fatal: attempt to fetch/clone from a shallow repository
WARN: failed to ensure package github.com/sampctl/pawn-stdlib: failed to ensure dependency from cache: unknown error: fatal: attempt to fetch/clone from a shallow repository
INFO: ensured dependencies for package
[root@localhost samp-bare]#
```

`/root/.samp/packages/sampctl/samp-stdlib/default` has a full and working git repository as well as `/pawn-stdlib/default`, but folders in `/root/samp-bare/dependencies` remain empty.

Plugin ensuring works flawlessly however, same with SA-MP binaries

**Comment by Southclaws** [comment]
This might be related to the version of Git that is on your system.

Annoyingly, the Git implementation that's built into sampctl doesn't support local repositories - aka repositories where the remote is a directory on your system. sampctl makes use of this git feature for the cache, each dependency is just a clone of a cached copy. This means that performing ensure now just calls `git`.

**Comment by Southclaws** [comment]
That issue is being tracked here: https://github.com/src-d/go-git/issues/847 but it doesn't look like there has been any movement, unless I implement it in a PR, we're stuck with a dependency on `git`.
