### ISSUE TITLE
failed to ensure scripts: filterscript

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#251]
#240, but not closed!

**Comment by Southclaws** [comment]
Do you have any pawn.json/files to reproduce this?

**Comment by TheManyula** [comment]
I ran into the same issue as described in https://github.com/Southclaws/sampctl/issues/240. His solution was to merely create a `gamemodes` folder but that didn't work for me.

You can check out [this repo](https://github.com/TheManyula/Modular-Pawn). If you try to run it with `sampctl p run`, you should get `failed to prepare package for running: failed to ensure runtime: failed to ensure scripts: filterscript 'flymode' is missing its .amx file from the filterscripts directory`.

**Comment by ADRFranklin** [comment]
Yes, because you have listed a Filterscript to be loaded, and it doesn't have an .amx file. Sampctl doesn't yet support compiling both gamemodes and filterscripts. I only supports gamemodes.

To get around this, you can change both `entry` and `output` to the path of the filterscript, compile that first, then once that has a .amx, you can change it back to the gamemode.

**Comment by TheManyula** [comment]
I followed the [filterscript documentation](https://github.com/Southclaws/sampctl/wiki/Filterscripts) step by step. I got the filterscript .amx by just changing into the filterscript's directory and building it. So, actually I do have the .amx file in the filterscripts folder.

![Folder](https://i.ibb.co/TtZ1Jpj/Unbenannt.png)

**Comment by ADRFranklin** [comment]
The .amx file does not seem to be in the same folder and instead looks like it is one directory up. 
To fix that, change the output field and remove the `../` from it. That will make it compile to the same directory which is correct.

**Comment by TheManyula** [comment]
Yes, it's in the parent directory as specified in the documentation.

I've removed the `../` in the `output` field and just moved the .amx to the same directory as the .pwn file. The issue persists, though.

**Comment by ADRFranklin** [comment]
The problem is your filterscript is in a subfolder called `flymode`. Sampctl does not seem to like the idea of sub folders and therefore it can't find it.

So the filterscript should be like this `filterscripts/flymode.amx` and not `filterscripts/flymode/flymode.amx`

**Comment by TheManyula** [comment]
That doesn't seem to be the issue either. I'll just quickly sum up what I've tried so far.

Both in a subfolder.
```
filterscripts/
└── flymode/
        ├── flymode.pwn
        └── flymode.amx
```

`.pwn` in subfolder, `.amx` in parent directory.
```
filterscripts/
├── flymode/
│      └── flymode.pwn
└── flymode.amx
```

Both in the `filterscripts/` directory, no subfolder.
```
filterscripts/
├── flymode.pwn
└── flymode.amx
```

None of the above work.

**Comment by ADRFranklin** [comment]
haha, I just realized something that everyone seems to forget.

You need to add this option to the pawn.json 
```
  "local": true,
```

I usually put it below `output` so it looks like this
```
  "entry": "gamemodes/main.pwn",
  "output": "gamemodes/main.amx",
  "local": true,
```

That should fix it

**Comment by TheManyula** [comment]
Damn, that was an easy fix. 😂 Resolved. 👍
