### ISSUE TITLE
This is a rip-off!

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#252]
From 2014:

https://github.com/DracoBlue/sampctl

:D

**Comment by Y-Less** [comment]
Time for that rename you keep promising I think.

**Comment by Southclaws** [comment]
I discovered this a few months into sampctl development (I even mentioned it on Discord), it's funny how we thought of the same name for similar projects - it was bound to happen I suppose!

I have considered renaming it to `pawnctl` for a few reasons... I'm not quite sure what the impact would be in regards to: package managers (brew, scoop, etc), users' PATH variables, and generally just users getting confused if they have both installed and aren't receiving updates.

**Comment by iiLearner** [comment]
y_ctl

**Comment by WoutProvost** [comment]
samp**ctl**
==>
samp**clt**

San Andreas Multiplayer Command Line Tool

Thank me later

**Comment by Y-Less** [comment]
> 
> 
> samp**ctl**
> ==>
> samp**clt**
> 
> San Andreas Multiplayer Command Line Tool
> 
> Thank me later

Command Line Interface Tool

**Comment by Jeroen52** [comment]
>>What tools do you use?

>Oh you know, Git, Pawn compiler, Sublime Text, sampCLIT

**Comment by Y-Less** [comment]
Don't forget GIMP for graphics.
