### ISSUE TITLE
0.3.DL ZIP package problem

### ISSUE THREAD

**Issue by DAKYSKYE** [Southclaws/sampctl#253]
when I set version to 0.3.DL in runtimes in pawn.json, I got this error
```
failed to prepare package for running: failed to ensure runtime: failed to ensure runtime binaries: failed to get runtime package: failed to get package 0.3.DL from cache: failed to unzip package C:\Users\Lasha Kanteladze\.samp\samp03DL_svr_R1_win32.zip: zip: not a valid zip file
```
but when I set version to 0.3.7, everything works perfectly.

**Comment by dhernandez0798** [comment]
Same for me. I'm receiving the same error.

**Comment by DAKYSKYE** [comment]
@dhernandez0798 you can place my uploaded .zip file manually to your .samp directory, that will fix problem. 
[samp03DL_svr_R1_win32.zip](https://github.com/Southclaws/sampctl/files/2367108/samp03DL_svr_R1_win32.zip)

**Comment by DAKYSKYE** [comment]
@Southclaws should close this issue cause it's fixed.

**Comment by DAKYSKYE** [comment]
Uhm, that issue is opened by me xD haha
