### ISSUE TITLE
Reload gamemode instantly (like reloadfs)

### ISSUE THREAD

**Issue by AmirSavand** [Southclaws/sampctl#259]

**Comment by Southclaws** [comment]
You can write `gmx` into an instance of sampctl and it will pass that along to the server instance.

**Comment by AmirSavand** [comment]
@Southclaws we've talked about this to invent a way to reload the gamemode as fast as reloading filterscripts.

**Comment by Y-Less** [comment]
FYI the gamemode reload delay was introduced to give clients time to reset everything, not just for the fun of it.  Having said that, YSF can already adjust the restart time.
