### ISSUE TITLE
Make runtime checksum match against entire archive, not just server binary

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#260]
The runtimes manifest here: https://github.com/sampctl/runtimes/blob/master/runtimes.json contains a `checksum` which one would assume is the checksum for the file at the URL but it's actually for the server binary inside the archive.

This should be changed so the checksum is against the entire archive.

**Comment by pawnoholic** [comment]
I have updated to the latest version but still get the error on OS Linux:
`failed to prepare package for running: failed to ensure runtime: failed to ensure runtime binaries: existing binary does not match checksum for version 0.3.DL`
