### ISSUE TITLE
Can't test-run package.

### ISSUE THREAD

**Issue by BronzeCheese** [Southclaws/sampctl#264]
Hey there,

I was working on https://github.com/BronzeCheese/samp-account-mysql/tree/dev and about to test what I currently have but I can't seem to run it because I keep getting the following error.

failed to prepare package for running: failed to ensure runtime: failed to ensure runtime binaries: existing binary does not match checksum for version 0.3.DL

What's wrong?

**Comment by spacemud** [comment]
Please direct all hate mail to @ADRFranklin

**Comment by ADRFranklin** [comment]
Haha, yeah that was my bad. I made a slight mistake in the checksum for 0.3.DL archive. It has been fixed so you will want to manually delete `runtime.json` from your `.samp` folder located in your users directory

**Comment by Southclaws** [comment]
I knew this would happen... unfortunately it was necessary.

Steps to resolve this issue:

- Open the cache directory, this is located in your personal user folder (`~/` on Linux, `%USERPROFILE%` on Windows) and is named `.samp`
- Locate the file named `runtimes.json`.
- Delete this file and re-run your sampctl command

sampctl will then re-download the runtimes manifest from this page and you're good to go!

**Comment by BronzeCheese** [comment]
Works, thanks!
