### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by yaziid** [Southclaws/sampctl#267]
Hello,
I'm trying to install sampctl by following the tutorial on the github wiki (https://github.com/Southclaws/sampctl/wiki/Windows).
When I run the installer (https://github.com/sampctl/installer/releases/download/0.3.0/sampctl-installer.exe), an error occurs: "the most recent information about the relase is not available" 
and I do not see where it can come from.
Thanks for your help :smile:

**Comment by Southclaws** [comment]
I can't find that error message in the codebase, it's most likely from GitHub. Maybe @BigETI knows more?

**Comment by Southclaws** [comment]
I suppose the answer is just to try again, it's most likely just a momentary outage on the GitHub API.
