### ISSUE TITLE
Package Init

### ISSUE THREAD

**Issue by DAKYSKYE** [Southclaws/sampctl#275]
Create a file too after package init. I mean, if there is no `.inc` or `.pwn` file(s) and user inputs the file name he/she want's to use, it also must be created automatically and not manually.
After `? No .pwn or .inc files - enter name for new script test.pwn`, **test.pwn** must be created too.

**Comment by Southclaws** [comment]
Yes this was always the intention, it should do that.

I plan to give a big update to `package init` so update it for newer features and make it generally more user-friendly.
