### ISSUE TITLE
Faster timeout on plugin redownload

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#278]
I'm at my parent's right now, and thus on a very bad connection (actually, I'm not sure why there's a correlation there, but there is).  Every time I start a server it redownloads the crashdetect plugin, despite the fact that I already have it.  I know this is done to ensure the latest one is always present for legacy components, but it takes a VERY long time, probably due to very long pauses.  I've loaded this page and written this issue while waiting for the server to start.

Is there a way to just give up after a brief timeout and use the cached version, or at least manually specify that it should use the cached version?

**Comment by Southclaws** [comment]
Currently it should only download the latest if there's no version specified in the package definition. I seem to remember there was a flag to control this. It's probably not good as default behaviour though so I probably should change it to only download when `--forceUpdate` is specified.
