### ISSUE TITLE
sampctl mapandreas 

### ISSUE THREAD

**Issue by lukassimoes** [Southclaws/sampctl#281]
Southclaws When I added the mapandreas file to sampctl it gave this warning >
```
WARN: failed to ensure package github.com/Southclaws/samp-plugin-mapandreas: failed to ensure asset: failed to get plugin Southclaws/samp-plugin-mapandreas from net: resource matcher 'MapAndreas-win-x86.zip' does not match any release assets from '[ MapAndreas-linux-x86.zip]'
```

and when I use the p build command, it looks like this

```
C:\Users\Venda\Desktop\SSS\gamemodes\ScavengeSurvive.pwn:139 (fatal) cannot read from file: "mapandreas"
Build encountered fatal error
```

 help me please,

**Comment by Southclaws** [comment]
There's currently no v1.2.2 version available for Windows: https://github.com/Southclaws/samp-plugin-mapandreas/releases lock to v1.2.1 for now and I'll update this when I release a v1.2.2 for Windows (tonight if I remember).

**Comment by lukassimoes** [comment]
How do you make this mistake? I've already changed the old version of windows, but the same error continues, do not identify

**Comment by Southclaws** [comment]
I released the new version while I didn't have a Windows machine available, that's how.

**Comment by Southclaws** [comment]
v1.2.2 now has Window binaries:

https://github.com/Southclaws/samp-plugin-mapandreas/releases/tag/v1.2.2

**Comment by almex1** [comment]
I have a problem with sampctl, in dependencies there is a file mapandreas, with includ, in plugins with plugin, but again when I type "sampctl p build" it comes out ```
"C: \ Users \ almir \ Desktop \ open.RP-master \ gamemodes \ main. pwn: 128 (fatal) cannot read from file: "mapandreas"
Build encountered fatal error
PS C: \ Users \ almir \ Desktop \ open.RP-master> "
```
