### ISSUE TITLE
A bit optimisation

### ISSUE THREAD

**Issue by dakyskye** [Southclaws/sampctl#286]
I don't like that
![image](https://user-images.githubusercontent.com/32128756/51790571-91778280-21b0-11e9-9397-5b52a85ec783.png)

so if I were, you, I would do:
```go
app.Name = "sampctl"
app.Usage = "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
```
instead of:
```go
app.Name = "sampctl"
app.Description = "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
```
and the result will be
![image](https://user-images.githubusercontent.com/32128756/51790556-6ab94c00-21b0-11e9-957c-c67a6f54740f.png)

**Comment by DAKYSKYE** [comment]
Definetely
