### ISSUE TITLE
sampctl package exit?

### ISSUE THREAD

**Issue by NexiusTailer** [Southclaws/sampctl#290]
It has a command "sampctl package init" to "link" some package to sampctl console, but there is no unlinking method to delete it somehow...

So actually the problem is: I've downloaded sampctl installer, run it from the windows command shell via "sampctl package init", it found some .pwn files in my local github repos and I've chosen one of them thus "linked" it to sampctl. But when I even deleted the repo manually from that folder, sampctl was still thinking that there is a "package" (despite the fact I couldn't do anything with it like "build", "run" as it has no more files in this directory or "uninstall" as it requires removing some dependencies when I just wanted to delete the repository itself). And at the same time when I type "sampctl package init" again now, it gives something like "Directory already appears to be a package" so I can't "unlink" it from sampctl explorer and create something new.

**Comment by DAKYSKYE** [comment]
I'm sure after removing _pawn.json_ from directory, sampctl will _init_ialise new package. I've experienced that many times.

**Comment by NexiusTailer** [comment]
> I'm sure after removing _pawn.json_ from directory, sampctl will **init**ialise new package. I've experienced that many times.

Unfortunately no, even without a whole repo folder, sampctl was still acting like it were intact.

**Comment by Southclaws** [comment]
There is no "linking" happening, sampctl is not a captive prompt and it does not do anything with your shell.

As DAKYSKYE said, all `init` does is create a `pawn.json` file - nothing else. To reverse that, you literally just delete `pawn.json`.

I have no idea what's happening in your issue description - sampctl certainly cannot "think"! You've probably just `cd`'d into a different directory or there's some strange filesystem caching going on in your OS. Given that you deleted the directory, I think what happened here is your shell was still open to the directory and you could still execute commands as if you were in the directory whereas in reality, the directory was moved to recycle bin.

**Comment by NexiusTailer** [comment]
> I have no idea what's happening in your issue description - sampctl certainly cannot "think"! You've probably just `cd`'d into a different directory or there's some strange filesystem caching going on in your OS.

Sure this obviously cannot "think", this is just a figure of speech as I couldn't discribe it properly in English, and most likely the problem was precisely in specified path to some folder that ceased to exist, the problem & question is just why this path haven't been reset (even after re-opening cmd and reinstalling the whole sampctl), I could not understand it even now.

P.s. I use Windows 10 x32 with default NTFS if it's important, nothing special.

**Comment by Southclaws** [comment]
sampctl is mostly stateless, it stores a tiny bit of global config in `~/.samp/config.json` but aside from that, it's effectively a fresh invocation each time you call it. There's nothing to "reset" because nothing is stored.

**Comment by Southclaws** [comment]
Is it possible for you to reproduce this minimally with a PowerShell script on AppVeyor? Unfortunately I don't have a Windows machine right now so there's not much I can do. I don't think this issue is related to sampctl though as none of the APIs in use behave this way and no other users have ever reported such strange behaviour. You might actually have better luck asking in a generic Windows board (StackExchange?) about CLI applications and what kinds of things may cause this behaviour.

**Comment by DAKYSKYE** [comment]
It's odd thats's even happening. `os.Open("pawn.json")` works same on Windows, MacOS and Linux.

**Comment by NexiusTailer** [comment]
Hm, ok. If sampctl doesn't make any operations with the path and it depends only on the windows console, it worth to close this issue for now but if something will happened again, I'll let you know with more specific and exhaustive information...
