### ISSUE TITLE
ColAndreas.cadb

### ISSUE THREAD

**Issue by TheManyula** [Southclaws/sampctl#292]
Where do I put the ColAndreas.cadb file in a sampctl package?

**Comment by Southclaws** [comment]
FYI: This is the sampctl issues section, it's for bugs with sampctl itself, not packages. Please open an issue on the ColAndreas repository.

As for the cadb file, you'll want to look into package resources in the wiki, these are additional files that can be shipped with packages such as mapandreas .hmap and geoip database. Check the mapandreas pawn.json for an example.
