### ISSUE TITLE
Monitoring changes

### ISSUE THREAD

**Issue by TheManyula** [Southclaws/sampctl#294]
Taking a look at [nodemon](https://github.com/remy/nodemon), I'd love to have something like this in sampctl. Of course, you can always `Ctrl+C` to terminate the server process and restart it but it's something that just adds that much more convenience to testing and the overall quality of life. Thoughts?

**Comment by Southclaws** [comment]
[`--watch`](https://github.com/Southclaws/sampctl#flags-10)
