### ISSUE TITLE
[RFC] Adding support for scripts

### ISSUE THREAD

**Issue by GiampaoloFalqui** [Southclaws/sampctl#299]
Inspired by https://getcomposer.org/doc/articles/scripts.md

It would be interesting if there was a support of scripts to run post-install to provision a package like:

- running database migrations
- fetching environment variables from a source of truth (AWS KMS, Vault, etc)
- custom bash scripts

The syntax could be something like what `composer.json` does.

```
{
    "scripts": {
        "pre-package-run-cmd": [
            "php artisan migrate"
        ],
        "pre-[command-syntax]-cmd": [
            "./bash-script"
        ],
    }
}
```

**Comment by ADRFranklin** [comment]
I suppose this wouldn't hurt, but the use case will be limited. Since this concept is usually reserved for packages that do more then just compile alone. Do to the limited behaviour a sa-mp package offers, I doubt this would be a highly wanted feature.

I can't think of anything I would want to do before and after a package is downloaded other then compile my gamemode. 

If you could give a valid example of a good use case for this, then I'm sure Southclaws or a contributor would see reason for adding it.

**Comment by GiampaoloFalqui** [comment]
I've given already three use cases already, one is running database migrations before running the package, which is key to make sure that the database schema is up to date with what the gamemode expects. 

Since SA-MP does not support database migrations in any way, I am using a component of Laravel (PHP) to handle them, so it would be nice if there was a hook available where I can run the command to run the database migrations.

**Comment by EOussama** [comment]
Bumping this, we could really use something like user-defined scripts, say, you want to run a template processor on your files...

**Comment by Southclaws** [comment]
There is actually an [undocumented field](https://github.com/Southclaws/sampctl/blob/e61c7ce053e4c8fc031754329c85bc799ecd310c/types/compiler.go#L15) in the build config named `plugins` (confusing name, I know) which is a list of commands to run before compilation. It was designed with template pre-processing in mind.

**Comment by EOussama** [comment]
> There is actually an [undocumented field](https://github.com/Southclaws/sampctl/blob/e61c7ce053e4c8fc031754329c85bc799ecd310c/types/compiler.go#L15) in the build config named `plugins` (confusing name, I know) which is a list of commands to run before compilation. It was designed with template pre-processing in mind.

Sweet, say; is it a feature to stay to is it planned to be removed? It being undocumented gives off deprecation vibes.

**Comment by Y-Less** [comment]
Or just gives off "couldn't be bothered to document it" vibes.  Why not document it, submit a PR with the documentation, and make it official?
