### ISSUE TITLE
.env file doesn't read, when using the newest 'server package' (pawn.json 'runtime')

### ISSUE THREAD

**Issue by BlackBank** [Southclaws/sampctl#308]
For some reason if i use the new way of setting up a server with pawn.json and the property 'runtime', it doesn't read my .env file and put those values empty in the server.cfg.

As example i use a .env file for the server variables **'rcon_password'** and **'password'**, so the server.cfg file look now like this:
```
rcon_password password
port 7777
hostname Servername here
maxplayers 50
```

As you can see the fields **rcon_password** and **password** are now after each other, with not the value i have entered in the .env file.

Is this a bug or is there nowadays an new way of handling those specific values?

btw, i use version 1.8.39 of sampctl.

**Comment by ADRFranklin** [comment]
This does work, I know for a fact it does. There are a few ENV Variables that are not correctly picked up.

**Comment by BlackBank** [comment]
> This does work, I know for a fact it does. There are a few ENV Variables that are not correctly picked up.

It also work for me if i use the old way: ```sampctl server ensure```, but with the new way ```sampctl package ensure``` not.

**Comment by ADRFranklin** [comment]
errm what? It only works for `sampctl p run`

**Comment by BlackBank** [comment]
> errm what? It only works for `sampctl p run`

Doesn't work either, and ```sampctl p ensure``` does configure my server.cfg, plugins, etc.

**Comment by ADRFranklin** [comment]
env variables are only used at runtime, `sampctl p ensure` does nothing with variables.

the ENV variables are used at runtime to modify the values in the `server.cfg`

**Comment by BlackBank** [comment]
> env variables are only used at runtime, `sampctl p ensure` does nothing with variables.
> 
> the ENV variables are used at runtime to modify the values in the `server.cfg`

Aha, i get it now, since it was working different with ```sampctl server``` i got confused. ```sampctl p run``` does indeed read the .env file when running the server. Thanks!
