### ISSUE TITLE
.env doesn't get read on Linux (Debian)

### ISSUE THREAD

**Issue by BlackBank** [Southclaws/sampctl#309]
On Linux(Debian) the .env doesn't get readed and being set up when i run the command: ```sampctl p run```.

This does work on Windows though.

I'm running the latest version of sampctl (1.8.39).

**Comment by Southclaws** [comment]
I've asked some sampctl users to confirm this. This never happened before and there should be no reason why there would be a difference by platform as the library that reads the `.env` file is just using standard file functions, nothing platform specific.

**Comment by ADRFranklin** [comment]
This is not true, I use env's on both Windows and Linux, and am using the latest version with absolutely no issues with it.

Please explain more with some examples of the issues you are facing.
