### ISSUE TITLE
Add "folders" array option to pawn.json runtime (similar to "files")

### ISSUE THREAD

**Issue by Jedrzej94** [Southclaws/sampctl#312]
> // some plugins require additional libraries (MySQL is a good example)
>       // so this field allows you to specify any additional files where the key
>       // is the path inside the archive and the value is the target path for
>       // when it gets extracted to the server directory. Most of the time,
>       // additional shared objects/DLLs should be in the same directory as the
>       // SA:MP server executable so there is no need to specify any additional
>       // directories in the value string.
>       "files": {
>         "deps/libcurl.dll": "libcurl.dll"

Some dependencies require folders (Audio Plugin - audiopackages). Package runtime doesn't support folders, but just files.

Can we add support for folders and files that are inside them or just folders without files and files could be added during "files" runtime.

**Comment by ADRFranklin** [comment]
@Jedrzej94 I just tested this, and turns out you don't need another config for this. Simply adding a folder as is, is enough to have it be copied.

```
        {
            "name": "^samp-audio-server-plugin-(.*).zip$",
            "platform": "linux",
            "archive": true,
            "includes": ["pawno/include"],
            "plugins": ["plugins/audio.so"],
            "files": {
                "audio.ini": "audio.ini",
                "audiopacks/": "audiopacks/"
            }
        },
```
