### ISSUE TITLE
Verbose startup issue

### ISSUE THREAD

**Issue by LewisBelton** [Southclaws/sampctl#319]
Running on Ubuntu 18.04, when running `sampctl p run --verbose` I get the following log, the Server never seems to start but I can't for the life of me figure out why.

- _https://hastebin.com/faruwufape.makefile_

**Comment by ADRFranklin** [comment]
What makes you think it isn't running? The logs show that the samp server was launched. Could you do `ps aux | grep samp` and make sure the process is still running?

**Comment by LewisBelton** [comment]
> What makes you think it isn't running? The logs show that the samp server was launched. Could you do `ps aux | grep samp` and make sure the process is still running?

Sorry I should have been more specific, we're running this using Pterodactyl so inside of a docker container - The Server shows as starting, and isn't accessible from the outside.

[https://i.imgur.com/l61lQgd.png](url)

**Comment by ADRFranklin** [comment]
I actually use Pterodactyl for a FiveM server, because a friend who isn't tech savy, needs an easy way to manage it. 

So I understand a lot about it. Anyway have you assigned the server a specified port, and have you made sure it's allowed through the firewall. Also what is your host provider? or are you running it locally?

**Comment by ADRFranklin** [comment]
The issue is, that SA-MP requires the internal port to be the same as the external port, else it breaks.

**Comment by LewisBelton** [comment]
> I actually use Pterodactyl for a FiveM server, because a friend who isn't tech savy, needs an easy way to manage it.
> 
> So I understand a lot about it. Anyway have you assigned the server a specified port, and have you made sure it's allowed through the firewall. Also what is your host provider? or are you running it locally?

The node is one of Hetzners Cloud VPS', which i've used before for this type of thing - Currently, the Server is assigned port `7777` as a primary port and no additionals. Firewall is all configured, everything is excluded as you would expect.

**Comment by ADRFranklin** [comment]
Is the internal port the same as the external port?

**Comment by LewisBelton** [comment]
Well, the configuration file for the Nest is below - All looks good to me:

`{
    "samp.json": {
        "parser": "json",
        "find": {
            "rcon_password": "{{server.build.env.RCON_PASSWORD}}",
            "maxplayers": "{{server.build.env.MAX_PLAYERS}}",
            "port": "{{server.build.default.port}}"
        }
    }
}`

It's set to `7777` in the `pawn.json`, yes.

**Comment by LewisBelton** [comment]
> > Is the internal port the same as the external port? So the port defined inside the docker image and is that port defined in the pawn.json for sampctl the same?
> 
> Well, the configuration file for the Nest is below - All looks good to me:
> 
> ```
>     "samp.json": {
>         "parser": "json",
>         "find": {
>             "rcon_password": "{{server.build.env.RCON_PASSWORD}}",
>             "maxplayers": "{{server.build.env.MAX_PLAYERS}}",
>             "port": "{{server.build.default.port}}"
>         }
>     }
> }```
> 
> It's set to `7777` in the `pawn.json`, yes.
> ```

Wait, surely `"samp.json":` should be `"pawn.json:"`?

**Comment by ADRFranklin** [comment]
I would suggest you access the machine and manually login to the container (make sure it's running) you can find it via `docker ps` and then find the name of the container and do `docker exec <name_of_container> /bin/sh` and than once inside try to ping the outside world. Just to make sure the container is able to access the outside world.

"samp.json" is deprecated, but will still work for now.

**Comment by LewisBelton** [comment]
> I would suggest you access the machine and manually login to the container (make sure it's running) you can find it via `docker ps` and then find the name of the container and do `docker exec <name_of_container> /bin/sh` and than once inside try to ping the outside world. Just to make sure the container is able to access the outside world.
> 
> "samp.json" is deprecated, but will still work for now.

Here's what happens.. 🤷‍♂ 
_- [https://i.imgur.com/Z3OW3l4.png](https://i.imgur.com/Z3OW3l4.png)_

**Comment by ADRFranklin** [comment]
Ignore the "Starting" text, that isn't always accurate as a lot of containers I run, says they are starting but run fine.

I need you to make sure that you have entered the container and ran something like `ping google.com` to make sure everything is okay inside the container. Ignore what Pterodactyl says for now, and concentrate on what Docker is saying.

**Comment by LewisBelton** [comment]
> Ignore the "Starting" text, that isn't always accurate as a lot of containers I run, says they are starting but run fine.
> 
> I need you to make sure that you have entered the container and ran something like `ping google.com` to make sure everything is okay inside the container. Ignore what Pterodactyl says for now, and concentrate on what Docker is saying.

Yeah I had that issue before, well what I was trying to show is after running `docker exec etc etc` it doesn't seem to throw me into the container so I can then run the ping test - Unless of course, I'm missing something,

**Comment by ADRFranklin** [comment]
Do you have discord? This isn't really a sampctl related issue and it would be better if we talked directly than here.

JustMichael#7884 (add me on Discord if you have it)

**Comment by LewisBelton** [comment]
> Do you have discord? This isn't really a sampctl related issue and it would be better if we talked directly than here.
> 
> JustMichael#7884 (add me on Discord if you have it)

Sure thing, request sent thanks.
