### ISSUE TITLE
pawnc.dll is missing

### ISSUE THREAD

**Issue by Brian-Less** [Southclaws/sampctl#322]
Only happen when open in this path
`C:\Windows\System32\config\systemprofile\.samp`

![https://i.ibb.co/vxbpBp8/1.png](https://i.ibb.co/vxbpBp8/1.png)

After build
`
\gamemodes
as
[LD_LIBRARY_PATH=C:\Windows\system32\config\systemprofile\.samp\pawn\3.10.9
DYLD_LIBRARY_PATH=C:\Windows\system32\config\systemprofile\.samp\pawn\3.10.9]
[C:\Windows\system32\config\systemprofile\.samp\pawn\3.10.9\pawncc.exe
`

**Comment by Southclaws** [comment]
Not sure why that's happening, I think others have reported this with 3.10.9 though.

**Comment by se8870** [comment]
Try running as administrator, if running as admin doesn't have any effect, i don't know what happen.

**Comment by Southclaws** [comment]
Never run processes as administrator, you're removing most of the protections supplied by your OS. If running a process as administrator fixes a problem, that's a security concern for the authors of the project. It should (almost) never be a solution to a problem.
