### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by unbelievable10** [Southclaws/sampctl#323]
WARN: failed to ensure package github.com/Zeex/samp-plugin-crashdetect:v4.19.4: no package definition file (pawn.{json|yaml|toml})

**Comment by Lilx9** [comment]
Maybe you input on dependencies like this:
`"github.com/Zeex/samp-plugin-crashdetect:v4.19.4",`

If so, change it to:
`"Zeex/samp-plugin-crashdetect:v4.19",`
