### ISSUE TITLE
branch dependency doesn't work

### ISSUE THREAD

**Issue by pawnoholic** [Southclaws/sampctl#326]
Hello, hello everyone.

I ran into this problem that the dependency on "pawn-lang/YSI-Includes@5.x" still load master branch.

![image](https://user-images.githubusercontent.com/32838352/72686309-16238500-3b15-11ea-86f6-7245e87c962d.png)

**Comment by ADRFranklin** [comment]
I'm pretty sure it doesn't lol. I use YSI 5.x with multiple gamemodes and have not experienced it downloading from the master branch.

What makes you think it's loading the master branch exactly?

**Comment by pawnoholic** [comment]
compare the structure and file names in the screenshot and in branch 5.x
________________________________

**Comment by pawnoholic** [comment]
I think that another dependency "Southclaws / progress2" points to "pawn-lang/YSI-Includes", so I get this problem, how can I get around it?

**Comment by Southclaws** [comment]
You can open a PR against progress2 to change it to 5.x or ensure 5.x comes last in the dependencies list so it overwrites older versions.

Unfortunately I never built version overrides for dependencies.
