### ISSUE TITLE
Installation in different location deleted files.

### ISSUE THREAD

**Issue by George480** [Southclaws/sampctl#336]
I decided to install sampctl but wanted to install it in my existed samp server folder. During the installation, I clicked on `Browse`, selected my folder, `Make new folder` and named it `sampctl` . After the installation was complete and opened my folder, everything was removed except the `sampctl` folder, `pawno\include` folders which were empty and `pawno_editor.exe` which I had renamed. Everything else was removed. I have a daily backup of my modular gamemode but I lost every filterscript.

**Comment by ADRFranklin** [comment]
What?

I am so confused at what you are trying to do? sampctl doesn't delete any files or folders. It just creates the folders if they do not exist. I am confused what you are refering to, when you say different locations? Are you talking about having multiple gamemodes and using sampctl inside each of them? or are you talking about having multiple versions of sampctl itself installed? 

If you are trying to use this in multiple gamemodes, then I think the way you are doing it is wrong. But please give more information about this.

**Comment by George480** [comment]
The installation path is by default on `c:\sampctl` and I used `Browse` to change it to my samp-server folder `C:\Users\...\Downloads\samp037` and create a folder `sampctl` in there.

**Comment by ADRFranklin** [comment]
you do realize that, that folder is used to store the `sampctl` executable alone right? not your gamemode or it's files?

**Comment by Southclaws** [comment]
I would not advise installing the sampctl binary into your project directory, it's software so should live in Program Files or a similar standardised location for binaries.

@ADRFranklin I think we should remove the UI installer or at least take a look at the code.

Scoop is the easiest and best, most support way to install.

**Comment by ADRFranklin** [comment]
@Southclaws Yeah I agree, the UI installer is not the best way, I think scoop is perfectly acceptable to use.
