### ISSUE TITLE
Check file existance after executing pre-build plugins

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#368]
I have a use case where I use the `plugins` field on my build configuration to generate the final files to be built. The problem is that the first time it fails due to the file itself not existing yet - It would exist if the pre-build plugins were executed after it though, which would sound like a valid use case for them:

`no such file 'prebuilt\OZ.pwn'`

**Comment by ADRFranklin** [comment]
I might deprecate that field and instead have a `pre-build` and a `post-build` section for specifying commands to run.

I think that would be a better solution.

**Comment by Southclaws** [comment]
The term `plugins` was always confusing anyway - pre/post build commands makes more sense.
