### ISSUE TITLE
Update repository to latest when using versioning with the --update flag

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/sampctl#390]
When you specify a dependency with a version, the repository stays at the same version as the reference for the latest release. This causes problems when a repository updates an include to fix an issue past the reference of the release and you are unable to pull the new changes down.

This would require getting the latest commit from the currently cached repository and comparing it against the remote repository. I think some json file that stores some data about the release file/archive should exist along side it, so that it can be used to keep track of which archives have been downloaded.

**Comment by Pedrilkov** [comment]
baaan
