### ISSUE TITLE
Idea of versioning

### ISSUE THREAD

**Issue by kubeeek** [Southclaws/sampctl#398]
Hello.

I cannot grasp the idea of versioning in the sampctl. I wanted to develop a server at 0.3.DL and how should I handle it in the sampctl config? I mean, every option different than 0.3.7 gives errors about dependencies and docs does not specify it too clear I guess.

```
"runtime": {
		"version": "0.3.DL"
}
```
Example error:
```terminal
$ sampctl package ensure
INFO: Downloading newest plugin because no version is specified. Consider specifying a version for this dependency.
INFO: Zeex/samp-plugin-crashdetect downloading plugin resource for windows
INFO: _/Godfather successfully ensured dependency files for github.com/Zeex/samp-plugin-crashdetect
INFO: Downloading newest plugin because no version is specified. Consider specifying a version for this dependency.
INFO: github.com/Zeex/samp-plugin-crashdetect downloading plugin resource for windows
WARN: failed to ensure plugin github.com/Zeex/samp-plugin-crashdetect failed to get plugin github.com/Zeex/samp-plugin-crashdetect from net: plugin does not provide binaries for target platform windows and version 0.3DL
```

**Comment by ADRFranklin** [comment]
Yes, this means that the repository does not have a release that is setup for 0.3DL. I would recommend asking the repo owners/maintainers to add a specific release for 0.3DL.

This was done on purpose to make sure people where getting the releases that matched their setup.

**Comment by kubeeek** [comment]
However, let's take an example that the repo doesn't have specified any
particular version of samp (so it also doesn't exclude any versions. in the
pawn.json) and sampctl still gives me error which I can't jump over even
when there is a compatibility between the versions, at least in theory. I
can't also pick older version by specifying the tag. It's little annoying
since I know what I want by picking particular version tag and I just wish
to keep the ease of crossplatform installation provided by sampctl. At the
current state, I will be forced to use another solution I guess because, if
there is no way to silence these errors, I highly doubt every package
maintainer will adapt update their configs and packages in reasonable
amount of time. Thank you for the reply.

sob., 25 lip 2020, 00:47 użytkownik JustMichael <notifications@github.com>
napisał:

**Comment by ADRFranklin** [comment]
You can always go back down to a previous version of sampctl for now. I'm sure I can make a quick patch version in the next few days to fallback if no version is provided.

**Comment by Southclaws** [comment]
All binaries work on 0.3.DL except for plugins that mess with memory. There should be no restriction, I don't remember ever adding one.
