### ISSUE TITLE
runtime directory error

### ISSUE THREAD

**Issue by tars-c** [Southclaws/sampctl#408]
INFO: build finished

ERROR: failed to copy amx file to temporary runtime directory: failed to copy AMX to temporary runtime area: open C:\Users\@username\.samp\runtime\0.3.7\gamemodes\test.amx: The system cannot find the path specified.
watch-run: executing package code

Is there a problem with the path or the pawn.json file?
Or Directory?

**Comment by Southclaws** [comment]
Either the source or destination path does not exist.

**Comment by tars-c** [comment]
@Southclaws 
I have corrected the path, but I keep getting the error.
Can I see a sample for pawn.json file?
Can I see a sample of using the --watch option?
You've already seen the Twitch video.

**Comment by tars-c** [comment]
@Southclaws 
I have set up the pawn.json file.
`
{
	"user": "tars-c",
	"repo": "roleplay-server",
	"entry": "rp_modes/roleplay.pwn",
	"output": "gamemodes/roleplay.amx",
	"dependencies": [
		"sampctl/samp-stdlib"
	],
	"local": true,
	"runtime": {
		"version": "0.3.7",
		"mode": "roleplay",
		"port": 7777,
		"hostname": "Roleplay Test Server",
		"maxplayers": 50,
		"announce": true,
		"query": true,
		"rcon": false,
		"logqueries": false,
		"maxnpc": 0,
		"stream_rate": 1000,
		"stream_distance": 200,
		"onfoot_rate": 30,
		"incar_rate": 30,
		"weapon_rate": 30,
		"chatlogging": true,
		"timestamp": true,
		"messageholelimit": 3000,
		"messageslimit": 500,
		"ackslimit": 3000,
		"playertimeout": 10000,
		"minconnectiontime": 0,
		"lagcompmode": 1,
		"connseedtime": 300000,
		"db_logging": false,
		"db_log_queries": false,
		"conncookies": true,
		"cookielogging": false,
		"output": true
	}
}
`

rp_modes fodler directory is same as sa-mp server root directory (gamemodes, scriptfiles, plugins, rp_modes...)
pwn file compiled sucess!
But I get an error in the output path. (*.amx file)

**Comment by Southclaws** [comment]
`failed to copy amx file to temporary runtime directory` implies it's trying to use the cache directory (aka, non-local) but you have `local` set to `true` so I don't know.

**Comment by ADRFranklin** [comment]
@tars-c this doesn't add up, could you run the same process again with the `--verbose` flag and paste the output either in pastebin or something similar so we can check what is happening?

**Comment by ADRFranklin** [comment]
@tars-c I think we have found a possible reason for this, a temp fix for you would be to remove the local setting, build/run with it, then add the local setting back to the config file.

**Comment by tars-c** [comment]
@ADRFranklin 
At first time, I didn't use the verbose option.
I set the output directory using the verbose option and ran the test.

All the errors have been fixed!
Thank you very much!

@Southclaws Thank you very much!!

the clsoed Issues.
