### ISSUE TITLE
Special characters aren't correct on sampctl

### ISSUE THREAD

**Issue by opysium** [Southclaws/sampctl#416]
When I start sampctl package run from Windows CMD or Visual Studio Code, special characters aren't correct on sampctl. But when I start samp-server.exe special characters are fine. It's not related to cmd chcp or UTF-8 because it's same when I use Windows-1254, it's related to sampctl I think. also those characters are Turkish special characters.

vscode terminal, sampctl package run
![image](https://user-images.githubusercontent.com/73075946/96376188-132df180-1186-11eb-811e-d7c2e4226df8.png)

sampctl from cmd, sampctl package run
![image](https://user-images.githubusercontent.com/73075946/96376171-fdb8c780-1185-11eb-800e-7ab8b198f118.png)

samp-server.exe
![image](https://user-images.githubusercontent.com/73075946/96376213-42446300-1186-11eb-8793-c78c9023fa06.png)

the code:
![image](https://user-images.githubusercontent.com/73075946/96376105-a87cb600-1185-11eb-852b-88048fdd4f6b.png)

**Comment by ADRFranklin** [comment]
In future can you post the actual code you are trying to make work? I can't reproduce these characters cause I have no idea where to get them from. 

Please do not post images of code.

**Comment by Southclaws** [comment]
This is odd because afaik the output is simply copied from the server process stdout to the sampctl stdout.

**Comment by ADRFranklin** [comment]
It's possible this not related to sampctl at all, and is related to the terminal/shell he is running it in. It could be forcing an encoding that is messing the output of sampctl.

The reason it is not shown in the "samp-server.exe" is because this is using the default windows command with default settings to output, which is normal for any console application.

**Comment by RiqueCool** [comment]
I'm having the same problem. I'm Brazilian, and when: Português -> Portuguï¿½s

**Comment by opysium** [comment]
I tried on Windows 10 Terminal (the app from Microsoft Store), built-in powershell, cmd, and i tried on windows 7 powershell and cmd. It's same, also the characters şğüçölöıİ you can try to print them.

**Comment by ADRFranklin** [comment]
https://i.imgur.com/Bhn7ily.png

This works fine for me?

**Comment by NegativeIQ** [comment]
Could be related to "System locale" in Windows itself. Basically its like fallback encoding (thats probably wrong explanation but i have no idea how to describe it)

Try changing it to yours (Change system locale button in picture) 
![image](https://user-images.githubusercontent.com/2947012/107562421-19862480-6be0-11eb-982d-f82578b7ed72.png)

That is from Windows 7, and you can find it in Control panel, Region and Language

**Comment by RiqueCool** [comment]
This last solution presented, causes a side effect on the system by renaming files a lot to random characters.

sampctl is not supporting other unicodes and this is an issue.
