### ISSUE TITLE
Failed to clone the repo

### ISSUE THREAD

**Issue by Pa4enka** [Southclaws/sampctl#434]
```
> sampctl p build
ERROR: failed to interpret directory as Pawn package: failed to ensure dependencies are cached: Failed to clone the repo
```
What am I doing wrong? After update.

**Comment by Southclaws** [comment]
Delete your cache directory. Details: https://github.com/Southclaws/sampctl/wiki/Cache

**Comment by Pa4enka** [comment]
Thank you very much! How can I get rid of dependency checking when sampctl p build? And why does my token get cleared every time?

Thanks again for the quick response))

**Comment by ADRFranklin** [comment]
Delete both your cache and your dependency folder and allow for to do a fresh pull of everything. The only reason this would happen is if it downloaded an empty archive or a corrupt file. Every single one of those repos requires downloading a plugin of which is either in an archive or a single file.

**Comment by Pa4enka** [comment]
Oh, it really works. Thanks. The problem has been resolved.

p.s: terminal vs code doesn't want to define the Cyrillic in the print func. I'm disappointed :(

**Comment by davidranich** [comment]
@ADRFranklin What if there's no cache folder? I checked the ~/.samp and there's no such directory anywhere I can find. I'm having the issue above as well. Any idea?
