### ISSUE TITLE
'sampctl' is not recognized as an internal or external command, Download SAMPCTLInstaller.exe

### ISSUE THREAD

**Issue by PutuSuhartawan** [Southclaws/sampctl#435]
![image](https://user-images.githubusercontent.com/71969427/111923738-8b089b00-8adb-11eb-9a79-3dcefb45ff11.png)

How to Download a Window release of sampctl and place the .exe file into the `sampctl` directory you created ?

**Comment by ADRFranklin** [comment]
You should read the Readme, it clearly stats to look at the wiki for installation instructions.
https://github.com/Southclaws/sampctl/wiki/Windows

**Comment by PutuSuhartawan** [comment]
I was do like the guide. But nothink file .exe for instal founded on sampctl ?

**Comment by PutuSuhartawan** [comment]
https://github.com/sampctl/installer/releases SAMPCTLInstaller.exe
