### ISSUE TITLE
failed to compile package entry: fork/exec

### ISSUE THREAD

**Issue by VIRUXE** [Southclaws/sampctl#438]
Hello. I'm trying to compile for the first time on linux with a `sampctl package build` and I got this error message: `failed to compile package entry: fork/exec /home/viruxe/.samp/pawn/3.10.10/pawncc: no such file or directory`

The file exists already.
![image](https://user-images.githubusercontent.com/1616657/123136055-6a3d4200-d44a-11eb-8926-f60c5d896350.png)

**Comment by ADRFranklin** [comment]
You need to install 32bit libraries with your OS, without them your OS has no way to run the compiler

**Comment by VIRUXE** [comment]
```
dpkg --add-architecture i386
apt update
apt install libc6-i386
```
Did the trick.
