### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by cuozgnguyen** [Southclaws/sampctl#439]
![image](https://user-images.githubusercontent.com/73394899/127370927-5c854740-8374-49c9-b77d-0b046cb9fa2f.png)
i can't build...

**Comment by Southclaws** [comment]
[Can you please post the errors as text](https://textnot.pictures)

**Comment by cuozgnguyen** [comment]
failed to compile package entry: exit status -1073741515

**Comment by ADRFranklin** [comment]
This means the pawn compiler itself, is unable to locate a shared dll it needs, this could be because you don't have the libraries needed on Windows for the dll to be imported by the pawn compiler.

**Comment by cuozgnguyen** [comment]
> This means the pawn compiler itself, is unable to locate a shared dll it needs, this could be because you don't have the libraries needed on Windows for the dll to be imported by the pawn compiler.


what do i need to make it milk, i tried many ways but it doesn't work

**Comment by Southclaws** [comment]
Find the Pawn compiler executable (it's in the .sampctl directory inside your user directory) and double click it in Explorer, it will then give you a better error message with the name of the dll required. I think it's MSVCR100.dll but it might be a later version,
