### ISSUE TITLE
Duplicate includes issues found with some repos

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/sampctl#441]
Due to the way sampctl handles downloading and extracting resources from releases, sometimes a release will contain the same include file as in the repository itself, this results in sampctl complaining of duplicate includes, because both the dependency path and the resources path both contain the same file.

To fix this we would need to figure out which path should be prioritised, meaning one of the paths would be dropped.

**Comment by Southclaws** [comment]
Note: if this check wasn't there, the pawn compiler would pick one and the user would not know which one (neither do I) so the sampctl check is there to prevent unexpected behaviour.

But yes, this should be fixed. If the resource contains a pawn include, that needs to be the one it chooses. The repository version may be a template or outdated. Plugin authors typically bundle all assets of the same version together.
