### ISSUE TITLE
a bug gm/fs

### ISSUE THREAD

**Issue by iyx** [Southclaws/sampctl#443]
about server.cfg: "Scripts do not have to be in the gamemodes or filterscripts folders. The information in server.cfg is a path, and can therefore use '..'."
This cannot be done with sampctl because automatically creates "gamemodes/filterscripts" files.

**Comment by ADRFranklin** [comment]
not a bug at all, but this was a design choice. I have removed to auto creation of folders already in the dev version
https://github.com/Southclaws/sampctl/commit/ac826831685fde3701c0248f8905cfc62cef6aee

**Comment by ADRFranklin** [comment]
Also you are wrong, you can change the Output/Entry sections in your pawn.json, that is where the files will be when server.cfg is generated.
