### ISSUE TITLE
Failing to ensure some repos.

### ISSUE THREAD

**Issue by VIRUXE** [Southclaws/sampctl#444]
```
WARN: failed to ensure package github.com/kolor4do/dialog-draw: no package definition file (pawn.{json|yaml|toml})
WARN: failed to ensure package github.com/kolor4do/dialog-draw: no package definition file (pawn.{json|yaml|toml})
WARN: failed to ensure package github.com/kolor4do/dialog-draw after 2 attempts, skipping
```
This happens with some repos. Can't remember the other ones this happens on but it's the same issue.

pawn.json seems valid.

**Comment by ADRFranklin** [comment]
This has been fixed in the dev repo already. I'm a little busy with other stuff right now, but I will make a new release in the near future. Just need a little time.

**Comment by VIRUXE** [comment]
Thank you.
