### ISSUE TITLE
Add option to hide/disable sampctl update notice

### ISSUE THREAD

**Issue by Se8870** [Southclaws/sampctl#449]
As the title says, it should have option to hide/disable the update release in case someone using the dev version or wanted to stay at older version.

This can be implemented by adding new configuration inside `sampctl/config.json`.

**Comment by Southclaws** [comment]
Yeah this would be good, a simple addition to silence this.

**Comment by ADRFranklin** [comment]
This feature has been added here: https://github.com/Southclaws/sampctl/commit/5083fc705671e2d5139a661c2711f9844b8f9e6e
