### ISSUE TITLE
Sampctl does not work [help]

### ISSUE THREAD

**Issue by Idsoal12** [Southclaws/sampctl#454]
Apparently sampctl is not working, I run any command and the following appears, I am new to this, I honestly do not know much.
Install sampctl manually since scoop did not allow me to install it.

![image](https://user-images.githubusercontent.com/63609791/147880741-94504d82-36f9-4416-9c3b-2ddff499a783.png)

**Comment by ADRFranklin** [comment]
This is because you need to go into your sampctl config file and remove the `metrics` field from it.

**Comment by Idsoal12** [comment]
> This is because you need to go into your sampctl config file and remove the `metrics` field from it.

yes it worked thanks.

I have a question, is it normal for this to happen when installing includes?
![image](https://user-images.githubusercontent.com/63609791/147892148-0276f0bf-1fa8-430c-ab0d-161cfd0210d4.png)
I think they are not added correctly

**Comment by Southclaws** [comment]
EOF is a network or filesystem error, probably either can't connect to github or can't write to your filesystem (most likely the former)
