### ISSUE TITLE
Fail to ensure dependencies due to unmatched checksum

### ISSUE THREAD

**Issue by duydang2311** [Southclaws/sampctl#457]
Hi,
I'm having a problem when building my project with github action, particularly `AGraber/sampctl-action`.
It was working a few weeks ago, but suddenly fails to ensure the dependencies right now.
I'm not sure if this has something to do with the action or the sampctl itself, but the action hasn't had any changes recently.
```
failed to ensure dependencies before build: failed to ensure runtime binaries: failed to get runtime package: failed to get package 0.3.7 from net: server binary does not match checksum for version 0.3.7
```

**Comment by RahRow** [comment]
about this issue i fixed it for my self in "Windows", then in any platform, you must find "sampctl" folder and place
[pawn-v3.10.10-windows.zip](https://github.com/Southclaws/sampctl/files/8025404/pawn-v3.10.10-windows.zip) zip file in there and i think it will work for you

**Comment by ADRFranklin** [comment]
@RahRow the pawn compiler is completely irrelevant to the issue here, the issue is talking about mismatching checksums for the server binaries.
