### ISSUE TITLE
failed to ensure

### ISSUE THREAD

**Issue by RahRow** [Southclaws/sampctl#459]
there is a problem, my problem is this that with Iran IP i have low download speed in my VPS, and i can't even download plugins from github and get errors like this:
![image](https://user-images.githubusercontent.com/58596268/153023250-9e231900-524a-49e6-b303-ad3d2d0483e5.png)

i used proxy still not working in VPS, but in my PC is ok,
then how can i install these plugins manually that the sampctl use cache instead of downloading, and the problem is this that the .samp folder does not exists in "root" home directory i mean "/root" and sampctl still works, so where it is ?!

**Comment by ADRFranklin** [comment]
your problem has to do with SSL, sampctl is not able to make a secure connection to the remote server aka github, so its timing out. This is not anything to do with sampctl, but to do with something blocking it, or being misconfigured

**Comment by RahRow** [comment]
Thanks, fixed with installing openssl
