### ISSUE TITLE
Help with exit status that I can't find anywhere that means

### ISSUE THREAD

**Issue by blaablaaaa** [Southclaws/sampctl#462]
Hello everyone, I have an exit status that I can't find what it means. I thought I did something wrong, but I've been trying 3 times and I can't understand what the problem is. Can anyone help me?

exit status 3221225477

**Comment by blaablaaaa** [comment]
Here's how it's easier for you 
pawn.json

{
	"user": "blaablaaa",
	"repo": "Viality",
	"entry": "gamemodes/main.pwn",
	"output": "gamemodes/main.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"oscar-broman/samp-weapon-config",
		"pawn-lang/YSI-Includes",
		"samp-incognito/samp-streamer-plugin",
		"Y-Less/sscanf",
		"katursis/Pawn.CMD:3.3.3",
		"NexiusTailer/Nex-AC",
		"pawn-lang/YSI-Includes",
		"Pottus/ColAndreas",
		"Southclaws/zcmd",
		"karimcambridge/SAMP-foreach",
		"GledersonDomingues/a_zone",
		"Crayder/Model-Sizes-Plus",
		"Zeex/samp-plugin-crashdetect"
	],
	"local": true,
	"runtime": {
		"version": "3.10.10",
		"mode": "server",
		"echo": "Executing Server Config...",
		"rcon_password": "123",
		"port": 7777,
		"hostname": "[V:RPG] Viality RPG",
		"maxplayers": 50,
		"language": "Balkanian",
		"mapname": "San Andreas",
		"weburl": "www.sa-mp.com",
		"gamemodetext": "Unknown",
		"announce": false,
		"lanmode": true,
		"query": true,
		"rcon": false,
		"logqueries": false,
		"sleep": 5,
		"maxnpc": 0,
		"stream_rate": 1000,
		"stream_distance": 800,
		"onfoot_rate": 40,
		"incar_rate": 40,
		"weapon_rate": 40,
		"chatlogging": false,
		"timestamp": true,
		"logtimeformat": "%H:%M:%S",
		"messageholelimit": 3000,
		"messageslimit": 500,
		"ackslimit": 5000,
		"playertimeout": 10000,
		"minconnectiontime": 0,
		"lagcompmode": 1,
		"connseedtime": 300000,
		"db_logging": false,
		"db_log_queries": false,
		"conncookies": true,
		"cookielogging": false,
		"output": true
	},
	"build": {
		"name": "",
		"version": "3.10.10",
		"args": [
			"-;+",
			"-(+",
			"-d3",
			"-Z+"
		],
		"includes": [
			"./includes/"
		],
		"compiler": {}
	}
}

**Comment by ADRFranklin** [comment]
No, I need the version of sampctl that you have. run `sampctl --version`

**Comment by blaablaaaa** [comment]
And okay sorry I'm just learning about the sampctl, version is 1.9.1

**Comment by ADRFranklin** [comment]
right, you need to update the latest version of sampctl. You are behind a version. Check the wiki for instructions on how to install.

**Comment by blaablaaaa** [comment]
Okay thanks, I'll update now
