### ISSUE TITLE
exit status 0xc0000005

### ISSUE THREAD

**Issue by blaablaaaa** [Southclaws/sampctl#463]
Can anyone help me what could be the problem with this exit status I downloaded and use sampctl 1.10.0

exit status 0xc0000005

**Comment by ADRFranklin** [comment]
It means you have an access violation, the program tried to access memory that didn't belong to it. So the pawn compiler wasn't invoked correctly or it couldn't access the dll properly.

**Comment by blaablaaaa** [comment]
How can I fix this ?

**Comment by ADRFranklin** [comment]
try removing spaces from your directory names, I've never tested with spaces before, so it's possible that could be an issue.

so rename "Viality RPG" to "VialityRPG" or something

**Comment by blaablaaaa** [comment]
I tried but nothing, again the same problem is probably something to fashion ... Nothing if it doesn't work doesn't work

**Comment by plakapenka** [comment]
isntall VCR

**Comment by blaablaaaa** [comment]
I installed again now for the second time but nothing helps the same exit status

**Comment by blaablaaaa** [comment]
This is not possible, whatever mode I put in sampctl, I can't compile it, I get the same exit status

**Comment by ADRFranklin** [comment]
I would need a lot more information about your computer and how your project is setup as well as your pawn.json file to continue helping you.

**Comment by blaablaaaa** [comment]
[pwn.json.txt](https://github.com/Southclaws/sampctl/files/8405242/pwn.json.txt)

This is pawn.json file

**Comment by blaablaaaa** [comment]
[pwn.json.txt](https://github.com/Southclaws/sampctl/files/8405244/pwn.json.txt)

This is another mode where I have the same problem. Here is the pawn.json file

**Comment by blaablaaaa** [comment]
_{
	"user": "zile42O",
	"repo": "jamaica-rpg",
	"entry": "gamemodes/JM.pwn",
	"output": "gamemodes/JM.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"Zeex/samp-plugin-crashdetect:v4.20",
		"oscar-broman/samp-weapon-config",
		"pawn-lang/YSI-Includes",
		"samp-incognito/samp-streamer-plugin",
		"Y-Less/sscanf",
		"katursis/Pawn.CMD:3.3.3",
		"NexiusTailer/Nex-AC",
		"pawn-lang/YSI-Includes",
		"pBlueG/SA-MP-MySQL:R41-4",
		"Pottus/ColAndreas",
		"Crayder/Model-Sizes-Plus"
	],
	"build": {
		"args": ["-;+", "-(+", "-d3", "-Z+"],
		"includes": ["./gamemodes/includes/"]
	},	
	"local": true,
	"runtime": {
		"version": "0.3.7",
		"mode": "server",
		"filterscripts": [			
		],
		"rcon_password": "password",
		"port": 7777,
		"hostname": "JAMAICA RPG: www.jamaica-ogc.com",
		"maxplayers": 100,
		"language": "Balkanski",
		"mapname": "San Andreas...",
		"weburl": "www.jamaica-ogc.com",
		"gamemodetext": "Jamaica 1.0",
		"announce": false,
		"lanmode": false,
		"query": true,
		"rcon": false,
		"logqueries": false,
		"sleep": 1,
		"maxnpc": 150,
		"stream_rate": 500,
		"stream_distance": 120,
		"onfoot_rate": 20,
		"incar_rate": 20,
		"weapon_rate": 20,
		"chatlogging": true,
		"timestamp": true,
		"messageholelimit": 3000,
		"messageslimit": 500,
		"ackslimit": 8000,
		"playertimeout": 10000,
		"minconnectiontime": 0,
		"lagcompmode": 1,
		"connseedtime": 300000,
		"db_logging": false,
		"db_log_queries": false,
		"conncookies": true,
		"cookielogging": false,
		"output": true
	}
}_

**Comment by ADRFranklin** [comment]
@blaablaaaa could you try with the latest version and tell me if you get the same error?
