### ISSUE TITLE
1.10.0 failing to ensure packages due to net: resource matcher

### ISSUE THREAD

**Issue by CnRXoMoX** [Southclaws/sampctl#465]
I don't know what's happening with the new version of sampctl, because one time I'm trying to ensure my files but the new version giving me a weird error

`INFO: CnRXomoX/lvrp-sampctl successfully ensured dependency files for github.com/IllidanS4/PawnPlus:v1.4.0.1
INFO: IllidanS4/YSF:v2.1 downloading plugin resource for windows
WARN: failed to ensure package github.com/IllidanS4/YSF:v2.1: failed to ensure asset: failed to get plugin IllidanS4/YSF:v2.1 from net: resource matcher 'YSF.*.zip' does not match any release assets from '[ YSF.zip]'
INFO: IllidanS4/YSF:v2.1 downloading plugin resource for windows
WARN: failed to ensure package github.com/IllidanS4/YSF:v2.1: failed to ensure asset: failed to get plugin IllidanS4/YSF:v2.1 from net: resource matcher 'YSF..zip' does not match any release assets from '[ YSF.zip]'
WARN: failed to ensure package github.com/IllidanS4/YSF:v2.1 after 2 attempts, skipping
INFO: CnRXomoX/lvrp-sampctl successfully ensured dependency files for github.com/Southclaws/samp-logger
updating runtimes list...
INFO: github.com/IllidanS4/YSF:v2.1 downloading plugin resource for windows
WARN: failed to ensure plugin github.com/IllidanS4/YSF:v2.1 failed to get plugin github.com/IllidanS4/YSF:v2.1 from net: resource matcher 'YSF_..zip' does not match any release assets from '[ YSF.zip]'
INFO: ensured dependencies for package`

Only on YSF, my only solution on this was reverting my sampctl back to 1.9.1

**Comment by ADRFranklin** [comment]
This has been fixed now.
