### ISSUE TITLE
failed to compile package entry: no such file or directory

### ISSUE THREAD

**Issue by MarcoGuzman0** [Southclaws/sampctl#467]
Hi everyone, I'm getting the next error while using **sampctl p build** with sampctl 1.10.0

_`failed to compile package entry: fork/exec /home/USERNAME/.config/sampctl/pawn/3.10.10/pawncc: no such file or directory`_

This is my pawn.json:

```
{
	"user": "MarcoGuzman0",
	"repo": "Server-Roleplay",
	"entry": "ServerRP.pwn",
	"output": "gamemodes/ServerRP.amx",
	"dependencies": [
		"pawn-lang/samp-stdlib",
		"Zeex/samp-plugin-crashdetect:v4.20",
		"pBlueG/SA-MP-MySQL:R41-4",
		"Awsomedude/easyDialog:2.0",
		"lassir/bcrypt-samp:v2.2.3",
		"katursis/Pawn.Regex:1.2.3",
		"katursis/Pawn.CMD:3.3.6",
		"NexiusTailer/Nex-AC",
		"samp-incognito/samp-streamer-plugin:v2.9.5",
		"Y-Less/sscanf:v2.11.4"
	],
	"local": true,
	"runtime": {
		"version": "0.3.7",
		"mode": "server",
		"rcon_password": "change",
		"port": 7777,
		"hostname": ".: Server RP :. En Desarrollo",
		"maxplayers": 20,
		"language": "Spanish",
		"mapname": "San Andreas",
		"weburl": "server-rp.test",
		"gamemodetext": "Roleplay ESP",
		"announce": true,
		"lanmode": false,
		"query": true,
		"rcon": false,
		"logqueries": false,
		"sleep": 5,
		"maxnpc": 0,
		"stream_rate": 1000,
		"stream_distance": 200,
		"onfoot_rate": 30,
		"incar_rate": 30,
		"weapon_rate": 30,
		"chatlogging": true,
		"timestamp": true,
		"messageholelimit": 3000,
		"messageslimit": 500,
		"ackslimit": 3000,
		"playertimeout": 10000,
		"minconnectiontime": 0,
		"lagcompmode": 1,
		"connseedtime": 300000,
		"db_logging": false,
		"db_log_queries": false,
		"conncookies": true,
		"cookielogging": false,
		"output": true
	}
}
```

I've already checked if pawncc is existing in sampctl main directory at pawn/3.10.10

What should I do to fix it?
I apologize for my poor English :s

**Comment by ADRFranklin** [comment]
Please run your command with `--verbose` flag after the command and paste the output here.

**Comment by MarcoGuzman0** [comment]
**sampctl b build --verbose**

`INFO: MarcoGuzman0/Server-Roleplay read package from directory /home/USERNAME/Documentos/Server-Roleplay
INFO: MarcoGuzman0/Server-Roleplay building dependency tree and ensuring cached copies
INFO: |- MarcoGuzman0/Server-Roleplay is parent
INFO: |- iterating 10 dependencies of MarcoGuzman0/Server-Roleplay
INFO: |-|- github.com/pawn-lang/samp-stdlib ensured
INFO: |-|- iterating 1 dependencies of sampctl/samp-stdlib
INFO: |-|-|- github.com/pawn-lang/pawn-stdlib ensured
INFO: |-|-|- iterating 0 dependencies of sampctl/pawn-stdlib
INFO: |-|- github.com/Zeex/samp-plugin-crashdetect:v4.20 ensured
INFO: |-|- added target path for resource includes: /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-plugin-crashdetect-fa6aea
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/Zeex/samp-plugin-crashdetect:v4.20 is a plugin
INFO: |-|- iterating 0 dependencies of Zeex/samp-plugin-crashdetect
INFO: |-|- github.com/pBlueG/SA-MP-MySQL:R41-4 ensured
INFO: |-|- added target path for resource includes: /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/SA-MP-MySQL-5f509e
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/pBlueG/SA-MP-MySQL:R41-4 is a plugin
INFO: |-|- iterating 0 dependencies of pBlueG/SA-MP-MySQL
INFO: |-|- github.com/Awsomedude/easyDialog:2.0 ensured
INFO: |-|- iterating 1 dependencies of Awsomedude/easyDialog
INFO: |-|- already visited github.com/sampctl/samp-stdlib
INFO: |-|- github.com/lassir/bcrypt-samp:v2.2.3 ensured
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/lassir/bcrypt-samp:v2.2.3 is a plugin
INFO: |-|- iterating 0 dependencies of lassir/bcrypt-samp
INFO: |-|- github.com/katursis/Pawn.Regex:1.2.3 ensured
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/katursis/Pawn.Regex:1.2.3 is a plugin
INFO: |-|- iterating 0 dependencies of katursis/Pawn.Regex
INFO: |-|- github.com/katursis/Pawn.CMD:3.3.6 ensured
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/katursis/Pawn.CMD:3.3.6 is a plugin
INFO: |-|- iterating 0 dependencies of katursis/Pawn.CMD
INFO: |-|- github.com/NexiusTailer/Nex-AC ensured
INFO: |-|- iterating 0 dependencies of NexiusTailer/Nex-AC
INFO: |-|- github.com/samp-incognito/samp-streamer-plugin:v2.9.5 ensured
INFO: |-|- added target path for resource includes: /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-streamer-plugin-7c00b9
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/samp-incognito/samp-streamer-plugin:v2.9.5 is a plugin
INFO: |-|- iterating 0 dependencies of samp-incognito/samp-streamer-plugin
INFO: |-|- github.com/Y-Less/sscanf:v2.11.4 ensured
INFO: |-|- added target path for resource includes: /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/sscanf-7b5726
INFO: |-|- ignoring platform mismatch windows
INFO: |-|- github.com/Y-Less/sscanf:v2.11.4 is a plugin
INFO: |-|- iterating 0 dependencies of Y-Less/sscanf
INFO: MarcoGuzman0/Server-Roleplay flattened dependencies to 11 leaves
INFO: no package definition file (pawn.{json|yaml})
INFO: no package definition file (pawn.{json|yaml})
INFO: no package definition file (pawn.{json|yaml})
INFO: Checking for cached package pawn-v3.10.10-linux.tgz in /home/USERNAME/.config/sampctl
INFO: setting permissions for binaries
INFO: Using cached package pawn-v3.10.10-linux.tgz
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/samp-stdlib
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/pawn-stdlib
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/SA-MP-MySQL
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/easyDialog
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/bcrypt-samp
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/Pawn.Regex/src
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/Pawn.CMD/src
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/Nex-AC/src/v1.9.59
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-plugin-crashdetect-fa6aea
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/SA-MP-MySQL-5f509e
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-streamer-plugin-7c00b9
INFO: using include path /home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/sscanf-7b5726
INFO: running pre-build commands
INFO: building MarcoGuzman0/Server-Roleplay with 3.10.10
INFO: executing compiler in /home/USERNAME/Documentos/Server-Roleplay as [LD_LIBRARY_PATH=/home/USERNAME/.config/sampctl/pawn/3.10.10 DYLD_LIBRARY_PATH=/home/USERNAME/.config/sampctl/pawn/3.10.10] [/home/USERNAME/.config/sampctl/pawn/3.10.10/pawncc /home/USERNAME/Documentos/Server-Roleplay/ServerRP.pwn -D/home/USERNAME/Documentos/Server-Roleplay -o/home/USERNAME/Documentos/Server-Roleplay/gamemodes/ServerRP.amx -d3 -;+ -(+ -\+ -Z+ -i/home/USERNAME/Documentos/Server-Roleplay -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/samp-stdlib -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/pawn-stdlib -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/SA-MP-MySQL -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/easyDialog -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/bcrypt-samp -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/Pawn.Regex/src -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/Pawn.CMD/src -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/Nex-AC/src/v1.9.59 -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-plugin-crashdetect-fa6aea -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/SA-MP-MySQL-5f509e -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/samp-streamer-plugin-7c00b9 -i/home/USERNAME/Documentos/Server-Roleplay/dependencies/.resources/sscanf-7b5726]
failed to compile package entry: fork/exec /home/USERNAME/.config/sampctl/pawn/3.10.10/pawncc: no such file or directory
`

**Comment by ADRFranklin** [comment]
can you go to this folder `/home/USERNAME/.config/sampctl/pawn/3.10.10/`
and run the command `file` on all files in that folder and provide the output for each (there should only be 2 files in it)

**Comment by MarcoGuzman0** [comment]
Sure!
**libpawnc.so**
`libpawnc.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=4bce23ac5387ee87712f412420429e74aa37fd6d, with debug_info, not stripped
`
**pawncc**
`pawncc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=3bd8b6bb8fbdf628914e3e7953bbdb97f6c123fc, with debug_info, not stripped`

**Comment by ADRFranklin** [comment]
By any chance did you activate 32bit libs for the linux distro you are on?

For example, on Ubuntu/Debian you need to run `dpkg --add-architecture i386` to enable 32bit libs, then you need to run `apt update` and then `apt install -y g++-multilib` to install the 32bit libs needed to run pawncc

**Comment by MarcoGuzman0** [comment]
Sorry, I missed to realize those steps before... but now it's solved, I'm very grateful to you!

Enabling i386 and installing `apt install -y g++-multilib` solved the problem, thanks! 😃

**Comment by ADRFranklin** [comment]
Alright, glad you got it working. 👍
