### ISSUE TITLE
Error due installation of include

### ISSUE THREAD

**Issue by njoBe1** [Southclaws/sampctl#468]
sampctl package install pawn-lang/YSI-Includes@5.x  //this is command
WARN: / Package Definition File does specify a value for `user`.
WARN: <none>/ Package Definition File does specify a value for `repo`.
ERROR: mkdir C:\Users\males\AppData\Roaming\sampctl\packages\pawn-lang\YSI-Includes\5.x:v5.05.0505: The directory name is invalid.
ERROR: Failed to clone the repo

I was installing YSI and this is error. Idk what it can be, im searching for 3hrs and still i can not see where is problem.

**Comment by ADRFranklin** [comment]
There is a known bug right now with using `install` to install a package, for now just manually go into your pawn.json and make sure YSI looks like this `pawn-lang/YSI-Includes:5.x`

**Comment by njoBe1** [comment]
i added it like this 

{
    "entry": "test.pwn",
    "output": "test.amx",
    "dependencies": ["pawn-lang/samp-stdlib", "pawn-lang/YSI-Includes:5.x" "Southclaws/formatex"]
  }

**Comment by ADRFranklin** [comment]
Solved in latest release

**Comment by Yorlandiscuba** [comment]
No help topic for 'package'
