### ISSUE TITLE
Problem running OpenMP

### ISSUE THREAD

**Issue by lucasgama335** [Southclaws/sampctl#472]
i was facing a problem running my game mode with openmp. vehicles were not being created. However, I realized that the problem only occurs when I run openmp with sampctl, if I download the files directly from the openmp repo and put it directly in my project everything works normally.

video demonstrating the problem: [https://youtu.be/TNElSY4_w7Q](url)

**Comment by ADRFranklin** [comment]
delete your cache and re-download the files.

**Comment by lucasgama335** [comment]
> delete your cache and re-download the files with `sampctl p ensure`

Now it's working!
