### ISSUE TITLE
Nix support for sampctl

### ISSUE THREAD

**Issue by Aiuraa** [Southclaws/sampctl#473]
It would be good if we can install sampctl via Nix since NixOS got popular and I'm using it.

**Comment by ADRFranklin** [comment]
You are free to build it yourself for armv7, but I don't have any plans to release another version of sampctl anytime soon.

**Comment by Aiuraa** [comment]
> You are free to build it yourself for armv7, but I don't have any plans to release another version of sampctl anytime soon.

NixOS is not for armv7 only BTW, and I'm using it for my PC which is x86_64, but sure!

**Comment by ADRFranklin** [comment]
if it supports x86_64 then it should work with the linux version of the release, else goreleaser doesn't support it, which means we will never support it

**Comment by Southclaws** [comment]
It would be great to see a Nix package for sampctl!

I'm not sure how many other users are using Nix so that's why it's tough to put the time and effort into supporting it but if you could contribute whatever manifest files necessary to make sampctl installable on Nix that would be welcome!

**Comment by Aiuraa** [comment]
I might reconsider this issue since i can't find a suitable method to install lib32 like other distros such as "Arch Linux", for example: `sudo pacman -S lib32-glibc`

But i'll come back later once i'm understand about this all, so i'll close the issue for now until i'm ready for it.
