### ISSUE TITLE
Sampctl stays as a background process - Linux (openmp)

### ISSUE THREAD

**Issue by DobbysGamertag** [Southclaws/sampctl#474]
When using `openmp` as a server version, it continues to stay open in the background when I use CTRL + C to close the server. SA:MP server runtime does not have this issue. 

```json
{
	"user": "DobbysGamertag",
	"repo": "test",
	"tag": "0.0.1",
	"entry": "gamemodes/test.pwn",
	"output": "gamemodes/test.amx",
	"dependencies": [
		"pawn-lang/samp-stdlib"
	],
	"runtime": {
		"version": "openmp"
	},
	"local": true
}
```

```txt
dobby in test at uwuntu on  master [?] 
➜ sampctl p run
Starting open.mp server (0.0.0.0)
```

* At this point, I use CTRL + C because I'm done testing, or whatever. 

```txt
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                               
 200718 dobby     20   0  189036 142924  15104 S   0.3   1.8   0:00.38 samp03svr                                                                                                                                                             
 ```
 
 Executing the binary manually, works (`./samp03svr`) however using the `sampctl p run` command does not. It only occurs when using `openmp` as the version. I don't want to have to use `kill -9` every time.

**Comment by Aiuraa** [comment]
Isn't this looks like openmp issue?

**Comment by Southclaws** [comment]
I think this is something related to open.mp not obeying sigkill or sigterm (I forgot which one sampctl sends)

cc @Cheaterman @amyrahmady
