### ISSUE TITLE
SAMPVOICE: files not moved

### ISSUE THREAD

**Issue by lucasgama335** [Southclaws/sampctl#475]
When installing sampvoice using sampctl p install, the .dll files are not moved to the plugins folder, and the compiler cannot find the includes.

Used version of sampvoice (opemmp): [https://github.com/AmyrAhmady/sampvoice](https://github.com/AmyrAhmady/sampvoice).

<p align="left">
	<img src="https://i.imgur.com/PGE0syn.png">
</p>
Without the .dll file in the plugins folder and without the include.

**Comment by ADRFranklin** [comment]
The repo does not contain a pawn.json file to tell sampctl about the release. You'd have to tell Amir about that and get him to add a pawn.json file.
