### ISSUE TITLE
"github.com/oscar-broman/md-sort: remote repository is empty"

### ISSUE THREAD

**Issue by leamir** [Southclaws/sampctl#478]
When trying to ensure YSI dependencies it says the repository [oscar-broman/md-sort](https://github.com/oscar-broman/md-sort) is empty. 

![image](https://user-images.githubusercontent.com/16721818/188297724-4995baaf-e6a4-46f5-a88d-92ccda8d623c.png)

**Comment by ADRFranklin** [comment]
Delete the cache for that package and re-run ensure. Also double check you are using the right repo.

**Comment by leamir** [comment]
It's probably cache (sampctl is reading from somewhere on C). Problem is there is no `.samp` folder in my `C:/Users/name`. Where can the cache folder be? I tried searching for it in my whole `C` drive

**Comment by ADRFranklin** [comment]
The cache folder is inside `%appdata%/sampctl` on windows.

**Comment by leamir** [comment]
Oh thanks, I suggest updating [Southclaws/sampctl/wiki/Cache](https://github.com/Southclaws/sampctl/wiki/Cache).

Clearing the cache fixed it. Would be nice a feature to auto-fetch if the repo is empty on the cache
