### ISSUE TITLE
 Problem with open.mp build 9

### ISSUE THREAD

**Issue by lucasgama335** [Southclaws/sampctl#479]
`sampctl p ensure`
it's not creating the components folder and moving the dlls from open.mp build 9

![Captura de tela 2022-09-08 201118](https://user-images.githubusercontent.com/23439087/189241692-f96ebd6f-0c13-433e-814d-80a57d1ed192.png)

**Comment by ADRFranklin** [comment]
sampctl isn't yet designed to work with opm, we currently use a hacky way to get it to work as it is.
