### ISSUE TITLE
Problem when trying to build.

### ISSUE THREAD

**Issue by TommS2** [Southclaws/sampctl#480]
Hello.
I've a issue when trying to build my gamemode.
I have been using sampctl in my main computer for a while and I didn't have any problem at all, but when trying to use it in my secondary computer (a laptop), it doesn't let me compile or build the gamemode. 
When I run `sampctl p build` command, it throws me the following lines:
`sampctl p build`
`updating compiler list...`
`failed to compile package entry: exit status 0xc0000135`

If you need any further information, just ask for it.
I appreciate any type of help.

**Comment by SrAerosol** [comment]
This error is fixed by copying and pasting the .dll **libpawnc.dll** and **msvcr100.dll**

**Comment by TommS2** [comment]
> This error is fixed by copying and pasting **libpawnc.dll** and **msvcr100.dll** in this folder **C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10**

Where can I find those files?

**Comment by SrAerosol** [comment]
it is in the zip file samp037_svr_R2-1-1_win32.zip when you enter you will find a folder called pawno and inside are those libraries

**Comment by SrAerosol** [comment]
> 


it is in the zip file samp037_svr_R2-1-1_win32.zip when you enter you will find a folder called pawno and inside are those libraries

**Comment by SrAerosol** [comment]
> > 
> 
> it is in the zip file samp037_svr_R2-1-1_win32.zip when you enter you will find a folder called pawno and inside are those libraries

If you can not
find these files or you don't know, I can send them to you without any problem

**Comment by SrAerosol** [comment]
> > This error is fixed by copying and pasting **libpawnc.dll** and **msvcr100.dll** in this folder **C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10**
> 
> Where can I find those files?

it is in the zip file samp037_svr_R2-1-1_win32.zip when you enter you will find a folder called pawno and inside are those libraries

**Comment by SrAerosol** [comment]
> 



> > > This error is fixed by copying and pasting **libpawnc.dll** and **msvcr100.dll** in this folder **C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10**
> > 
> > 
> > Where can I find those files?
> 
> it is in the zip file samp037_svr_R2-1-1_win32.zip when you enter you will find a folder called pawno and inside are those libraries

If you can not
find these files or you don't know, I can send them to you without any problem

**Comment by TommS2** [comment]
> This error is fixed by copying and pasting **libpawnc.dll** and **msvcr100.dll** in this folder **C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10**

I installed those files in that directory and it still throws the same problem.

**Comment by SrAerosol** [comment]
> C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10

try to open pawncc.exe and tell me what happens

**Comment by TommS2** [comment]
> > C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10
> 
> try to open pawncc.exe and tell me what happens

The problem 0xc0000135 it's fixed, but now it throws 'failed to compile package entry: exit status 0xc000007b'.

**Comment by SrAerosol** [comment]
Do you have these 3 libraries in sampctl's pawno folder: **pawnc.dll**, **msvcr100.dll**, and **libpawnc.dll**?

> > > C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10
> > 
> > 
> > try to open pawncc.exe and tell me what happens
> 
> The problem 0xc0000135 it's fixed, but now it throws 'failed to compile package entry: exit status 0xc000007b'.

**Comment by TommS2** [comment]
> Do you have these 3 libraries in sampctl's pawno folder: **pawnc.dll**, **msvcr100.dll**, and **libpawnc.dll**?
> 
> > > > C:\Users\user\AppData\Roaming\sampctl\pawn\3.10.10
> > > 
> > > 
> > > try to open pawncc.exe and tell me what happens
> > 
> > 
> > The problem 0xc0000135 it's fixed, but now it throws 'failed to compile package entry: exit status 0xc000007b'.

Yup, all of them.

**Comment by SrAerosol** [comment]
I have uploaded my pawno folder, copy and paste it in your folder, this is the link:

> > ¿Tienes estas 3 bibliotecas en la carpeta pawno de sampctl: **pawnc**.dll, **msvcr100.dll** y **libpawnc.dll**?
> > > > > C:\Usuarios\usuario\AppData\Roaming\sampctl\pawn\3.10.10
> > > > 
> > > > 
> > > > Intenta abrir PawnCC.exe y dime qué pasa
> > > 
> > > 
> > > El problema 0xc0000135 que está solucionado, pero ahora arroja 'error al compilar la entrada del paquete: estado de salida 0xc000007b'.
> 
> Sí, todos.


I have uploaded my pawno folder, copy and paste it in your folder, this is the link: [https://github.com/SrAerosol/sampctl-pawn](url)

**Comment by TommS2** [comment]
> I have uploaded my pawno folder, copy and paste it in your folder, this is the link:
> 
> > > ¿Tienes estas 3 bibliotecas en la carpeta pawno de sampctl: **pawnc**.dll, **msvcr100.dll** y **libpawnc.dll**?
> > > > > > C:\Usuarios\usuario\AppData\Roaming\sampctl\pawn\3.10.10
> > > > > 
> > > > > 
> > > > > Intenta abrir PawnCC.exe y dime qué pasa
> > > > 
> > > > 
> > > > El problema 0xc0000135 que está solucionado, pero ahora arroja 'error al compilar la entrada del paquete: estado de salida 0xc000007b'.
> > 
> > 
> > Sí, todos.
> 
> I have uploaded my pawno folder, copy and paste it in your folder, this is the link: https://github.com/SrAerosol/sampctl-pawn

Your repo solved my problem, thank you 👍
