### ISSUE TITLE
Find a solution, "init" and then "build" it up like this, how to fix it?

### ISSUE THREAD

**Issue by ChamoyZ** [Southclaws/sampctl#481]
![image](https://user-images.githubusercontent.com/59873775/198892930-d960e284-4b89-4c59-a185-21e6cd4455f9.png)

**Comment by Southclaws** [comment]
That exit status is directly from the compiler process. I'm not sure what that specific code means though. It starts with `0xc0` which often implies a missing resource, maybe a .dll file.

**Comment by ChamoyZ** [comment]
It can now be fixed. Caused by mistake I forgot to install "VC++".
