### ISSUE TITLE
authentication required / failed to interpret directory as Pawn package: failed to ensure dependencies are cached: Failed to clone the repo

### ISSUE THREAD

**Issue by Nelsonpwn** [Southclaws/sampctl#492]
Hello, I need help in solving the above problem. I want to compile a mod using sampctl v1.11.0 and I want to compile a samp script with sampctl. 
I can't get the script to compile and I need a little help. Pawn.json says where server.cfg and samp-server.exe is is that correct?

I am new to using these features. Thanks in advance.

PS: I'm using visual studio code, in it I'm connected to the Repository on Github. I installed sampctl according to the tutorial on the forum. (https://github.com/Southclaws/sampctl/wiki/Windows)
![Screenshot_5](https://user-images.githubusercontent.com/7648921/217234930-d04931a4-e64d-4cbe-a2f4-d79f4860ee2a.png)

Pawn.json: https://pastebin.com/XtSSKqs5

**Comment by cristiifrim** [comment]
try deleting the file dependencies from the project if it exists.

then go to %appdata% and delete sampctl file from there and run sampctl ensure/init again

**Comment by ADRFranklin** [comment]
You are getting this because `Bronzal/mSelection` doesn't exist, the repo has been deleted or made private.
