### ISSUE TITLE
Faild to compile package entry: exit status_access_violation

### ISSUE THREAD

**Issue by d1cnn** [Southclaws/sampctl#499]
![image](https://user-images.githubusercontent.com/76929063/233759288-2684061f-74dc-4486-bb39-c0256ddd5782.png)
after i compile the gta-open it shows this on the picture
and if i compile other gamemodes there is no exit status error

**Comment by ADRFranklin** [comment]
The information provided here is only what we get back from the compiler, this is not a problem with sampctl, but with the pawn compiler and your gamemode.
