### ISSUE TITLE
This project needs a documentation about samp.json

### ISSUE THREAD

**Issue by BigETI** [Southclaws/sampctl#5]
I cba to peek into settings.go everytime to know the structure used in samp.json.

**Comment by Southclaws** [comment]
It mirrors the server.cfg format quite closely, it's just annoying how the `gamemode` list differs from the `filterscripts`/`plugins` lists, all the rest is exactly the same. Integers are used where integers would be and floats are used where floats normally would be (`stream_distance` etc).

But, I will add documentation to the readme of course still. But not too in depth, just enough to go over the slight oddities with `gamemodes`.

**Comment by BigETI** [comment]
```JSON
{
	"ackslimit": 3000,
	"announce": false,
	"bind": "",
	"chatlogging": true,
	"conncookies": true,
	"connseedtime": 300000,
	"cookielogging": false,
	"db_log_queries": false,
	"db_logging": false,
	"filterscripts": [],
	"gamemodes": [],
	"gamemodetext": "Unknown",
	"hostname": "SA-MP Server",
	"incar_rate": 30,
	"lagcompmode": 1,
	"language": "SA-MP Server",
	"lanmode": false,
	"logqueries": false,
	"logtimeformat": "[%H:%M:%S]",
	"mapname": "San Andreas",
	"max_players": 50,
	"maxnpc": 0,
	"messageholelimit": 3000,
	"messageslimit": 500,
	"minconnectiontime": 0,
	"nosign": "",
	"onfoot_rate": 30,
	"password": "",
	"playertimeout": 10000,
	"plugins": [],
	"port": 8192,
	"query": false,
	"rcon": false,
	"rcon_password": "",
	"sleep": 5,
	"stream_distance": 200,
	"stream_rate": 1000,
	"timestamp": true,
	"weapon_rate": 30,
	"weburl": "www.sa-mp.com"
}
```

This is what I got right now. I hope this is the correct structure used in `settings.go`.

**Comment by Southclaws** [comment]
Added to readme.md
