### ISSUE TITLE
Fails to load pugins 

### ISSUE THREAD

**Issue by EnrikasVai** [Southclaws/sampctl#516]
Hello, when i run my server I get this in the console: 

----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

language = ""  (string)

Server Plugins
--------------
 Loading plugin: mysql
  Failed.
 Loaded 0 plugins.

Started server on port: 7777, with maxplayers: 50 lanmode is OFF.

Filterscripts
---------------
  Loaded 0 filterscripts.

Script[gamemodes/scriptas.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0

Does anyone have any idea why it fails to load the mysql plugin?
pawn.json:

"user": "EnrikasVai",
	"repo": "RPGSERVAS",
	"entry": "scriptas.pwn",
	"output": "gamemodes/scriptas.amx",
	"dependencies": [
		"openmultiplayer/omp-stdlib",
		"pawn-lang/samp-stdlib@open.mp",
		"pawn-lang/pawn-stdlib@open.mp",
		"pBlueG/SA-MP-MySQL/releases/tag/R41-4:R41",
		"Awsomedude/easyDialog:2.0"
	],

**Comment by Wisnoe26** [comment]
"pBlueG/SA-MP-MySQL:R41-4",
