### ISSUE TITLE
Unable to convert from string to type string

### ISSUE THREAD

**Issue by Dayrion** [Southclaws/sampctl#61]
Hi.
I found your project very interesting so I tried out. So I tried to setup my test server with `sampctl server init --dir [direction]`.
I got stopped by an error happens when I select a plugin. Those plugins are already downloaded and the script is already made. I'm just testing sampctl (and see if I can familiarize with it and maybe use it for further utilisation), that's why there are already these plugins and the script.
The error:
![Error](https://i.gyazo.com/223d4d8e7a475678ea8463c246ba0d40.png)

PS: A more complete tutorial would be appreciate for people, like me, who have no idea how to use what you made 😃

**Comment by Southclaws** [comment]
Well that's quite a cryptic error! I'll investigate, thanks for reporting it.

And yes, I'm planning to work on the wiki a bit more now that the package management features are stable.

I haven't worked much on the `sampctl server *` commands much recently so I should probably give them a bit of love and update/test them more!

**Comment by Southclaws** [comment]
This will be fixed in release 1.5.5!
