### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Romz24** [Southclaws/sampctl#65]
Hello! Can you explain what it is and what is it for?

**Comment by Southclaws** [comment]
Hi, the [readme](https://github.com/Southclaws/sampctl/blob/master/README.md) should explain what the tool is, if it's difficult to read or doesn't explain it very well then please let me know so I can improve it!

**Comment by Southclaws** [comment]
I've rewritten parts of the readme and updated it with some demo videos of how some of the tools are useful. Hope it helps! Please re-open/reply here if you have further questions.
