### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#67]
Some of this stuff would be interesting to try on Pawn code: https://code.visualstudio.com/docs/extensionAPI/language-support

It might mean the Pawn-Parser project isn't as vital after all...

**Comment by J0shES** [comment]
# **I SAY** 

+ [x] **YES**
+ [x] **YES**
+ [x] **YES**
+ [x] **YES**
+ [x] **YES**
+ [x] **YES**
