### ISSUE TITLE
maybe remove ambiguity with `gamemode` and `gamemodes`

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#8]
```json
"gamemode": "bare"
```
vs
```json
"gamemodes": ["bare"]
```

**Comment by BigETI** [comment]
hi

**Comment by BigETI** [comment]
My app is going to do `"gamemodes": ["somegamemode"]` anyway. I hope the `gamemode` attribute doesn't override the values passed to server.cfg.

**Comment by Southclaws** [comment]
Removed gamemode in that last commit
