### ISSUE TITLE
Implement authentication credentials/ssh via config

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#82]
Authenticated pulls for private repos (#60) requires authentication - now that config.json is implemented (on dev) this should now be possible.

**Comment by pawnoholic** [comment]
Nice, support for private repositories is required. Thank you, really looking forward to.

**Comment by Southclaws** [comment]
@pawnoholic what is your preferred authentication method for git? ssh or http/user/password?

**Comment by Southclaws** [comment]
This is resolved now, just needs some unit tests and it will be available in the 1.6.5 release.
