### ISSUE TITLE
Better initial readmes

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#83]
Doing `sampctl package init` asks for a package name, then procededs to produce readmes full of `your library here`.  It looks like it is trying with `sampctl package install {{.User}}/{{.Repo}}`, but doesn't actually replace anything.

**Comment by Southclaws** [comment]
I've just implemented that into `dev` - it's coming in the next release!

**Comment by Southclaws** [comment]
1.5.16 resolves this.
