### ISSUE TITLE
Rapid prototyping

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#87]
I very very frequently create small modes to test one little thing, like an experiment with a tag or confirmation that `6 * 9 == 42`.  It would be nice to have a common test configuration, so I can set it up as normal as a package with dependencies and the like.  But then, when I create a new file, have an option like `sampctl temp file.pwn`, which uses that common package to build the given file, run the server once, and exit.  Then I can bind that in my editor and for any random new file of 5 lines be able to fire off a server execution in seconds and not even worry about includes (as long as all the ones I'm likely to want (fairly consistent set) are pre-defined).

**Comment by Southclaws** [comment]
I'll get this in the 1.6 release. I think the best way to do this would be to create a "template" package from an existing package, which copies the `pawn.json`/`pawn.yaml` file and the `dependencies/` directory to `~/.samp/tempPkg` (or something).

So the command structure would be:

- `sampctl package template create` - use in an existing package to make that package a template.
- `sampctl package template run file.pwn` - use anywhere to build+run the file in the template package

**Comment by Southclaws** [comment]
and of course, you can use the short aliases if you're in a hurry: `sampctl p t run file.pwn`

**Comment by Southclaws** [comment]
Basic features added in 1.6.2, I might add more convenience features to help install packages and stuff to template packages but for now you simply pass `--dir` to any sampctl package commands `cd` to the template package directory to modify it.
