### ISSUE TITLE
"username" is a terrible default.

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#90]
The `sampctl package init` wizard is quite nice, with sane defaults 99% of the time, except for when entering your username.  The default should either be pulled from git global config, or not present at all, thus forcing the user to enter something.  It is too easy to hit enter too much and get your username set to "username".

**Comment by Southclaws** [comment]
Ah I forgot about git global config! Yes, this is a fair point it should be empty to begin with (once you enter it, it stores the value you enter in ~/.samp/config for future quick usage).
